### ISSUE TITLE
Annotations on an image

### ISSUE THREAD

**Issue by demstanford** [BYU-ARCLITE/Ayamel-Examples#224]
Annotations aren't working, EXCEPT FOR  two specific userstories where they do work:
1. User adds image annotation to an image
2. User adds video annotation to an image

So I thought I'd create a bug report about how even though those two things work on an image, these two things do not:
1. User adds audio annotation to an image
2. User adds text annotation to an image

...But it's not that surprising, since audio and text annotations don't work on any other type of content either. So yeah. Anyway, thanks for your good work!

**Comment by gliese1337** [comment]
This functionality should now be handled by captioning.
