### ISSUE TITLE
Define dependencies with NPM or Bower

### ISSUE THREAD

**Issue by DavidMikeSimon** [BYU-ARCLITE/Ayamel-Examples#237]
Rather than a script that does manual checkouts of depended-upon repositories, it would be more reliable and safer to use a mechanism that defines dependencies explicitly and recursively, such as [npm](https://www.npmjs.org/). This has a few advantages:

1. Sub-dependencies are recursively installed
2. The particular version of interest can be locked, rather than this project being subject to anything that breaks in the master branch of the dep
3. It's the standard way of doing things, which makes it easier for new developers and also to use other tools such as Travis.

**Comment by gliese1337** [comment]
It is time to admit that this is just not going to happen.
