### ISSUE TITLE
Batch upload not working

### ISSUE THREAD

**Issue by oxyfay** [BYU-ARCLITE/Ayamel-Examples#254]
I am trying to upload all of the Arabic videos onto Ayamel using a PC in the Chrome browser (problem also exists in Firefox).  I have all of the URLs from the server and I upload them through the batch upload function, and it looks like everything worked.  I am automatically redirected to the Ayamel home page with a pop-up that says, "You will be notified when the batch is done uploading".  However, I never got notified and none of the videos were uploaded.  However, when I batch upload only 15 or so videos at a time (not 367), this sometimes works.  I go through the same process and am again redirected to the Ayamel homepage and eventually, I received a notification that the batch is done uploading.  However, this notification is sometimes delayed.  I have received it days after the upload is completed.  Sometimes I receive it within 8 minutes of starting the upload.

**Comment by gliese1337** [comment]
I'm just gonna consider this rolled in to #168 .
