### ISSUE TITLE
Non-CAS users cannot request to become a teacher or anything else

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#311]
When logged in via Google or username/password, the "Request Additional Permissions" box will not show up.

Here is a Firefox CAS user on the left and a (top-right) password user, and a (bottom-right) Google user and what they see:
https://www.dropbox.com/s/8aw4ayge8rvjf0p/Screenshot%202014-08-25%2012.19.07.png?dl=0

Attempting to directly access permissions by going to:
http://sartre3.byu.edu:9006/user/permission/request
Redirects non-CAS users to the front page with an error.

**Comment by gliese1337** [comment]
This has been fixed for I-don't-know-how-long.
