### ISSUE TITLE
LMS connection not working

### ISSUE THREAD

**Issue by demstanford** [BYU-ARCLITE/Ayamel-Examples#414]
I added my course Test Course (http://sartre3.byu.edu:9006/course/6) to a class on LearningSuite, who told me it saved successfully. But then to check, I went to Student View to check and clicked on the assignment I'd just made to connect to my course. 
![screen shot 2014-11-01 at 2 21 22 pm](https://cloud.githubusercontent.com/assets/5481914/4873331/96f0e81c-620d-11e4-8ef6-32e2cad0627f.png)
It took me to the Sartre3 homepage with a notification banner at the top saying I couldn't do that. Normally it just takes me to the course I connected it to.
![screen shot 2014-11-01 at 2 21 33 pm](https://cloud.githubusercontent.com/assets/5481914/4873332/96f0fece-620d-11e4-9188-4f148e93f0d7.png)

**Comment by gliese1337** [comment]
On further investigation, it looks like the problem lies in the call to oauthRequest.verify in LMSAuth.ltiAuth.

We should see if there were any changes to that code around last October that may have introduce the problem.

**Comment by DigitalProf** [comment]
All,

As Jean-Luc Picard so famously says,

“Make it so!”

:-)

Who can handle this? As I believe I have mentioned, this is very high on our priority list, given that BYU Independent Study needs LTI with HTTPS. The latter has been holding us up, but we have an interim solution in place there.

Many thanks to all!

Cheers,

Prof Bush

**Comment by gliese1337** [comment]
I have scoured our commit history, and I just don't see anything that's an obvious candidate for the regression. I could've just missed it, but it doesn't look like any real significant changes were made to the LTI system in between the time that it was first implemented and the time that this problem was first reported.

In addition to LMSAuth and the OAuth code, we might need to look at the code that generates the LTI embedding info, as well. The error could be on either end, or both.

**Comment by JKJensen** [comment]
This issue is not working on both the main site and the beta site. Because it is broken in both places this can be downgraded from Critical to Priority.

**Comment by schyatt** [comment]
I disagree. Last semester, this was working on the production site and many
teachers need this feature for their upcoming classes (like Dr. Bush's
French 311 class). Also, this is one of the only things we are waiting for
before Independent Study is willing to use Ayamel for some of their
courses. So I'd leave it as critical, but it is up to you guys.

On Wed, Aug 26, 2015 at 2:43 PM, Jeffrey Jensen <notifications@github.com>
wrote:

> This issue is not working on both the main site and the beta site. Because
> it is broken in both places this can be downgraded from Critical to
> Priority.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/414#issuecomment-135165225>
> .
>



-- 
Shari Hyatt

**Comment by DigitalProf** [comment]
@schyatt : Things seem to be working on the Beta site. Let's test it on the Beta site.

**Comment by schyatt** [comment]
I am still getting the "Oh snap. You cannot do that" error when I try to connect to content on the beta site from learning suite via an lti. I cleared my browser and still got the same error.

**Comment by verdude** [comment]
It's not going to work on the beta site yet. Learning Suite has yet to include the port number of a url in their request. We're just waiting on them, so it's not our issue anymore.
