### ISSUE TITLE
Mac-Safari- Cannot click on transcripts more than once.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#442]
Tested on Mac-Pro in the Lab.

When I click on a line in the transcript I can click on it once and it will lead me to that location in the video, however, any other lines I click on the transcript will not bring me to the location in the video.

It only works once.
Testing on this video:
http://sartre3.byu.edu:9006/content/388

**Comment by gliese1337** [comment]
It seems to have fixed itself.
