### ISSUE TITLE
Opening up a lot of different annotations can cause the video player to freeze.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#452]
So I turn on the subtitles "work-CaptionsForNationsVideo" and "Example Subtitles" and I click around on every piece of annotated content. The content shows up, it works.
http://sartre3.byu.edu:9006/content/208

But when I hit the play button the video will not play. It will stay stuck on the moment I clicked the annotation.
Tested on the Mac Pro in the Lab. Only happens in Chrome.

**Comment by gliese1337** [comment]
Don't see any memory leaks building up. There does, however, seem to be a problem with navigating via the transcript not working properly. It's just possible that the errors thrown there might be causing this problem.

**Comment by gliese1337** [comment]
Closed due to low priority combined with no obvious attack strategy and the fact that this is likely to fix itself as other things are improved.
