### ISSUE TITLE
Add annotation content via url

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#455]
It would be nice if you had the option to add a video with a url like you are able to with images. That way you could pull something straight from Youtube without having to upload it to your content on Ayamel beforehand.  
Content annotation:
https://www.dropbox.com/s/wgukc4tumckz0s0/Screenshot%202015-01-12%2013.14.51.png?dl=0

Image annotation with the url option:
https://www.dropbox.com/s/ujr3vt79n126ak4/Screenshot%202015-01-12%2013.16.26.png?dl=0

**Comment by gliese1337** [comment]
Image annotations need to be deprecated. We should just have Text (possibly Rich Text), and everything else grouped together under Content annotations.
I'm gonna leave this open, though, because it is still a good idea to allow creating new content directly in the annotation editor.
