### ISSUE TITLE
Option to edit an annotation track from the annotation menu

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#456]
It would be nice if you had the option to edit an annotation track right from this page: 
https://www.dropbox.com/s/bpqj773v5d6g9l2/Screenshot%202015-01-09%2014.50.45.png?dl=0
That way you wouldn't have to hit launch annotation editor, hit edit to choose which track, and then have to save and select which track you want to save the changes to.

**Comment by gliese1337** [comment]
We have to keep the regular editor no matter what, so this would have to be an added option, not a replacement. It also results in breaking the parallelism between how you access the annotation editor and how you access the subtitle editor. All in all, I suspect the increase in complexity is not worth it. There is, however, plenty of room for addressing these UX issues in other ways.
