### ISSUE TITLE
Mac-Chrome- Captionaider won't overwrite subtitles to the server

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#457]
This was on ayamel.byu.edu/content/1718 in Japanese.

Captionaider will not overwrite a previously saved subtitle track to the server.

However, when we download our saved file later, all the subtitles do appear, but not in the video itself.

**Comment by gliese1337** [comment]
This sounds like a caching issue. If you can download them, then they were properly saved. Have you checked the video again later (after refreshing, or clearing cache, or on a different computer) to see if the updated subtitles appear (I would check myself, but I have no idea what you changed)?

**Comment by gliese1337** [comment]
Closed due to lack of detail. Probably the same issue as #470 .
