### ISSUE TITLE
Issue with Ayamel Reports and Incorrect Dates

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#464]
We have a bug that we need to get worked out as soon as we can. When we download the stats to see how users are interacting with the videos on Ayamel, we noticed that the date is completely wrong. I put specific notes in the spreadsheet (it won't let me attach it, but I emailed it to Logan)(located on sheet 1), but basically the report reports that people who in reality used Ayamel in Fall of 2014 used it in 2015, and students who actually used it in 2015 used it in 2014. Also, it always says they used it at 7:00. 

Also, the sheet entitled event data is what we downloaded from Ayamel.
This was my process for downloading the stats from Ayamel:
1.       Go to Admin Dashboard
2.       Select Content
3.       Find the movie
4.       Hit View
5.       Hit Edit
6.       Select View Stats
7.       Select Download
8.       Save as an excel file
9.       Open it

**Comment by gliese1337** [comment]
This appears to have stopped happening all on its own. My best guess is something up with the system clock on Sartre3. The 7:00 thing, by the way, is not a bug- it doesn't mean they used it at 7:00, it means the timestamps were recorded in the UTC-7 (that is, Mountain Standard) time zone.
