### ISSUE TITLE
Brightcove Uploading Problem

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#473]
We are having a problem uploading videos to Brightcove via Google Chrome but not via Firefox, and Dr. Bush was wondering if you had any ideas what the difference might be. I have emailed you a screencast of the problem, because I felt that would explain the process better.

**Comment by gliese1337** [comment]
Closing because this is not a problem with Ayamel. We should get somebody involved with Brightcove to take a look at it, though.
