### ISSUE TITLE
Be able to upload content in a course setting

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#476]
In a course setting, there's no way to upload new content.

For example the "add content" button in a course lists content already on Ayamel to add:
https://www.dropbox.com/s/ge0s920z3w6mjhe/Screenshot%202015-02-06%2011.27.57.png?dl=0

On the select content screen:
https://www.dropbox.com/s/n4cyiza66n7s57d/Screenshot%202015-02-06%2011.27.48.png?dl=0

There should be a button added called "Upload new content." It would redirect to the add content screen:
https://www.dropbox.com/s/fe8hcjcjyxzp8vx/Screenshot%202015-02-06%2011.29.10.png?dl=0

The user could add/link their content and once finished, the content would already be added to the course.

**Comment by verdude** [comment]
I added this functionality to the dev site. If it doesn't work the way it was intended to, let me know.
