### ISSUE TITLE
Show all tracks- switch the "save" and "close" locations

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#477]
In captionaider a user can click on that "laptop" button and show all tracks. However, the "show" and "close" option need to be switched around.
https://www.dropbox.com/s/9za664s0cos220f/Screenshot%202015-02-06%2011.37.22.png?dl=0

Right now a user has to click once again somewhere outside the selection box before seeing the "save" button.
https://www.dropbox.com/s/9kpeqbgdixjb5cd/Screenshot%202015-02-06%2011.37.45.png?dl=0

Switching the location of those two options would save them a click.

**Comment by gliese1337** [comment]
Hm. Is it acceptable if we just move the selection box so it doesn't cover those buttons instead?

**Comment by JKJensen** [comment]
That'll work.
