### ISSUE TITLE
Annotation editor: Once highlighted a word, be able to close the box by pressing escape

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#479]
https://www.dropbox.com/s/hc9gn74loassgr3/Screenshot%202015-02-06%2011.56.48.png?dl=0
That screen in the annotation editor can't be escaped from by pressing "escape."

**Comment by gliese1337** [comment]
In fairness, neither can any other dialogs on the whole site, as far as I'm aware. It would be inconsistent to add that behavior here and not do it everywhere else. So, we've got to decide if it's worth that amount of effort.

**Comment by JKJensen** [comment]
Actually, you can escape from all the dialogue boxes on the video player, like "Configuration" and "Add to Course." 

Are those dialogue boxes calling some kind of "escape" function that you could use again for the annotation editor?

**Comment by verdude** [comment]
Works if the focus is not on the popup textarea.
