### ISSUE TITLE
User is prompted to save unsaved work, but user just saved the work

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#481]
I can click on save to server, and save to disk, but no matter how much I save I always get this warning.

Is there anything checking that the users work was just saved without any changes done to the subtitles?
https://www.dropbox.com/s/kpzpyjg8z6dnqnt/Screenshot%202015-02-06%2016.17.40.png?dl=0

**Comment by gliese1337** [comment]
There is indeed something checking that. Evidently, it is not working properly. What browser & platform is this for?

**Comment by JKJensen** [comment]
Mac Firefox

**Comment by gliese1337** [comment]
Turned out not to be Mac/Firefox-specific after all. An error in the code for the New Track button was adding a hidden empty file to the under/redo tracker which was never saved.
