### ISSUE TITLE
Multiple subtitle tracks on a small screen can't be captioned

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#484]
On Firefox it's impossible to scroll down with multiple captions open. So if I create multiple subtitle tracks the video player is obscured by captionaider.
Two Tracks:
https://www.dropbox.com/s/wm63zkbh38qva0m/Screenshot%202015-02-10%2015.12.11.png?dl=0

Three Tracks:
https://www.dropbox.com/s/556520zf5o4v2yw/Screenshot%202015-02-10%2015.15.38.png?dl=0

At a certain point it's impossible to type into the box my captions without removing a subtitle track. This is mostly an issue for small screens.

We should still be able to scroll the top frame, the video player, to the bottom so the subtitle portion of the video can be accessed.

**Comment by gliese1337** [comment]
Confirmed that this is working in both Firefox and Chrome on Windows. Must be something weird with the Mac version of Firefox.

**Comment by gliese1337** [comment]
Can't replicate. May have resolved itself.
