### ISSUE TITLE
Cannot create annotations in annotation editor

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#485]
I open the annotations editor and I can highlight a word and an input box will pop up, but the highlight will not be created. It won't show up as pink like it's supposed to.

http://sartre3.byu.edu:9006/content/421

I'm trying to highlight Japanese words and those words are on the second page of annotations.

**Comment by verdude** [comment]
Just make sure that you choose the subtitle track language as the annotation language before you try to annotate it.
