### ISSUE TITLE
Video/ content Annotations mess up the player

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#487]
So I sent you an email with a screen cast of the problem. Basically, after you click on a video/ content annotation in either chrome or firefox with a PC, it messes up the player of the original video once you try to pause the annotation and go back to the video. The subtitles and the transcript no longer progress, and you cannot pause the video. You can't jump to places in the video by clicking on the transcript either.

**Comment by gliese1337** [comment]
The screencast does not show the URL bar or the title of the video. Can you provide a URL to the page where this bug was occurring? Have you replicated it on any other videos?

**Comment by shyatt** [comment]
Here is the url:http://ayamel.byu.edu/content/1791
The annotation is on the second line of the transcript. I have not tried it
on any other videos, but I will.

Thanks,
Shari

On Mon, Feb 16, 2015 at 12:27 PM, Logan Kearsley <notifications@github.com>
wrote:

> The screencast does not show the URL bar or the title of the video. Can
> you provide a URL to the page where this bug was occurring? Have you
> replicated it on any other videos?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/487#issuecomment-74560155>
> .
>



-- 
Shari Messick

**Comment by gliese1337** [comment]
This seems to have resolved itself. Might've been something wrong with the YouTube player (since both main video & the annotation video on that page were from YouTube) which is just not an issue anymore since we re-wrote the YouTube plugin.
