### ISSUE TITLE
Video content won't play

### ISSUE THREAD

**Issue by mariahb** [BYU-ARCLITE/Ayamel-Examples#488]
I added a new music video called "Me ei olla enää me" to FINN 340. I uploaded the video using the URL option. The video uploaded to Ayamel just fine, but when I click on the music video icon to play it, it won't play.

**Comment by gliese1337** [comment]
Can you provide a link to the content page? I cannot find that video on either site.

**Comment by mariahb** [comment]
Here it is! 

http://ayamel.byu.edu/content/1808 <http://ayamel.byu.edu/content/1808>

**Comment by DigitalProf** [comment]
For what it is worth, I was able to put the video on the Beta site and it works!
http://sartre3.byu.edu:9006/content/426

**Comment by gliese1337** [comment]
It's a YouTube video. That explains everything. This is the bug that we already fixed, where some YouTube videos wouldn't play because YouTube deprecated their old player. As soon as we push the latest changes to production, this will go away.
