### ISSUE TITLE
Transcript has letters on the end that aren't supposed to be there

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#500]
So I was making Dr. Jones' videos have bigger subtitles and ran into the issue that each line on the transcript now has a "\n" tacked on to the end of it. The "\n" doesn't show up on the subtitles, just on the transcript, so I can't figure out how to get rid of it.
https://cloud.githubusercontent.com/assets/10120523/7378708/b859ab26-edac-11e4-96ef-8a78e08e71eb.png
Here is the url for the specific video:  http://ayamel.byu.edu/content/1775

**Comment by daganrh** [comment]
When are you coming in today, Santi and I cannot convince play and the dictionary glider to talk to eachother to open up the test page.

Dagan
