### ISSUE TITLE
Add content language to admin dashboard

### ISSUE THREAD

**Issue by verdude** [BYU-ARCLITE/Ayamel-Examples#501]
List content language in the content menu as another column.

**Comment by daganrh** [comment]
Hey I forgot my phone, I am at the bowling alley in the Wik, down by the pool tables, come grab me when you get here

Dagan Holbrook
801-369-2652
daganholbrook@gmail.com

**Comment by gliese1337** [comment]
We'll want to revisit this later, but it *does* work now, so closing.
