### ISSUE TITLE
Multiple Entries in a Course for One Student

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#504]
In the Spanish Course I created, a person added the course, and now it says there are three of her. Link for course:
http://ayamel.byu.edu/course/346
The name is Lynn Oliva

**Comment by verdude** [comment]
She isn't in the course anymore. I'm not sure how to replicate this.

Are there any other courses that have multiple users in them?

**Comment by shyatt** [comment]
Yes, in English Public Content there is a student in there twice:  Mohamad
Ansary
https://ayamel.byu.edu/course/331

On Fri, Jun 19, 2015 at 5:32 PM, Santiago Verdu <notifications@github.com>
wrote:

> She isn't in the course anymore. I'm not sure how to replicate this.
>
> Are there any other courses that have multiple users in them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/504#issuecomment-113671656>
> .
>



-- 
Shari Hyatt

**Comment by verdude** [comment]
Users won't be added to the course if they already pertain to it.

I'm not sure if we want to hide the multiple users or if we want to go into the database and delete them from the course with some query. So for now, I let the multiple users show up in the course.

Also, I deleted the duplicate entry for the English Public Content course.
