### ISSUE TITLE
Add UI for Viewing/Editing CaptionAider Line Buffers

### ISSUE THREAD

**Issue by gliese1337** [BYU-ARCLITE/Ayamel-Examples#506]
This can't be done directly in the TImeline Editor code, because it requires rendering UI elements outside of the timeline. There might be some alterations to the TImeline Editor to better accommodate this functionality, though.

**Comment by dro248** [comment]
Are you available any time today?

**Comment by JKJensen** [comment]
This was already finished.

**Comment by JKJensen** [comment]
Issue #771 explains this feature better.
