### ISSUE TITLE
Mac- All browsers- Full screen is not going to full screen

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#511]
When a user presses the full screen button the video only takes up the left half of the screen.
http://gyazo.com/47d79cf58d4d0d8d5b1359b17959dd8d

http://ayamel.byu.edu/course/348/content/2129

**Comment by daganrh** [comment]
I am seeing the same thing on Chrome. Currently full screen player may be
built like that to allow translations and definitions to still be displayed
to the side of the screen, without having to but that functionality has not
been built in yet.

Any other input Logan or Dr. Bush?

**Comment by verdude** [comment]
Fixed on the beta site.
