### ISSUE TITLE
CaptionAider-Timeline Editor- Change the color of the tracks.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#514]
The captions color should be a blue gradient, and the metadata color a green gradient.

http://gyazo.com/28ad4b81397a6bccf4263c06c18f6c1c

Right now the Metadata is Yellow.

**Comment by gliese1337** [comment]
That image shows two Chapters tracks, one of which happens to be *named* "Metadata". Metadata tracks are indeed green.
