### ISSUE TITLE
Mac-Chrome/Firefox Brightcove Player will not play

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#517]
On Mac Chrome/Firefox the Brightcove Player will not play the video. The user will be left with a black screen.
https://www.dropbox.com/s/ofifco4p3jptqo3/Screenshot%202015-06-04%2016.59.28.png?dl=0

This is the video I'm using: https://ayamel.byu.edu/course/349/content/2117
It does work in Safari.

**Comment by gliese1337** [comment]
Looks like an HTTPS error. If it's not fixed already, it probably will be once Brightcove finishes transitioning our stuff on their CDN.
