### ISSUE TITLE
Dictionary Lookup is not looking up any information

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#518]
Dictionary Lookup is not loading any information.

http://gyazo.com/1484b5f3b757b713ebac815fc0f27f42

Here is a video I was working from: https://ayamel.byu.edu/content/1862

**Comment by JKJensen** [comment]
On Chrome it will work if the user clicks on the shield and "Loads unsafe scripts"
![loadunsafescripts](https://cloud.githubusercontent.com/assets/5481718/7996811/be5d8e8c-0ae1-11e5-9ee8-96a8da8ff4ea.gif)

**Comment by DigitalProf** [comment]
This was the result of the problems we had with conversion to HTTPS, which has been fixed.
