### ISSUE TITLE
Subtitles onYoutube videos will show up in Ayamel video player

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#519]
I think the gif explains this best:
http://gyazo.com/9313bdc3592e3e158ee88e475c544ba0

![gyazoayamelyoutubeproblem](https://cloud.githubusercontent.com/assets/5481718/7996680/4ca7689a-0ae0-11e5-950d-4930b208781b.gif)

If a Youtube video has captions on them, those captions will show up in Ayamel.

There needs to be a way of disabling those Youtube captions so that they don't interfere with Ayamel's subtitles.

The video we are using is here: https://ayamel.byu.edu/course/356/content/2423

**Comment by shyatt** [comment]
I had this problem as well, but I found if I had captions enabled on
youtube, they would show up on Ayamel, but if I disabled them on YouTube,
then they didn't show up on Ayamel.

On Thu, Jun 4, 2015 at 5:41 PM, JKJensen <notifications@github.com> wrote:

> I think the gif explains this best:
> http://gyazo.com/9313bdc3592e3e158ee88e475c544ba0
>
> [image: gyazoayamelyoutubeproblem]
> <https://cloud.githubusercontent.com/assets/5481718/7996680/4ca7689a-0ae0-11e5-950d-4930b208781b.gif>
>
> If a Youtube video has captions on them, those captions will show up in
> Ayamel.
>
> There needs to be a way of disabling those Youtube captions so that they
> don't interfere with Ayamel's subtitles.
>
> The video we are using is here:
> https://ayamel.byu.edu/course/356/content/2423
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/519>.
>



-- 
Shari Hyatt

**Comment by gliese1337** [comment]
This is not something that we have control over. YouTube allows its users to turn YouTube captions on and off, and we can't override that.
