### ISSUE TITLE
Bug with Annotations

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#521]
When I am in the annotation editor and create an annotation, it doesn't change the word to pink after I save it. Even after I quit and come back in to edit the annotation track, they don't show up in pink, but they do show up in the captions when I watch the video. This is with all types of annotations.
URL for video: https://ayamel.byu.edu/course/311/content/131
Words annotated:  Malgré and France

**Comment by verdude** [comment]
fixed on the beta site

**Comment by shyatt** [comment]
It isn't working on the production site either.

On Thu, Jun 11, 2015 at 4:20 PM, Santiago Verdu <notifications@github.com>
wrote:

> Closed #521 <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/521>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/521#event-328994628>
> .
>



-- 
Shari Hyatt
