### ISSUE TITLE
No Ability to Remove Administrator rights

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#524]
We accidentally made Dr. Jones an Administrator. How do we remove his admin rights?

![screenshot 2015-06-09 10 53 48](https://cloud.githubusercontent.com/assets/5481718/8064123/f36e2804-0e95-11e5-9422-312c247d82e2.png)

How difficult would it be to prevent this from happening in the future? I know we don't want ourselves to accidentally delete all administrators. But it would still be a good idea to be able to remove admin rights.

Maybe we could have a "minimum" number of admins? And no one can delete any more admin rights if the number of admins falls below 4.

**Comment by verdude** [comment]
Right now, removing permissions through the admin dashboard seems to have no effect.

**Comment by gliese1337** [comment]
The minimum number of admins is 1. If you are an admin, you cannot remove your own admin rights. This guarantees that there will always be one admin left.
