### ISSUE TITLE
Differentiate public courses by "Featured Courses" and "Other Courses"

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#525]
When a user clicks on "public courses," it should lead them to a page with "Featured Courses" and "Other Courses."
![publiccontentidea](https://cloud.githubusercontent.com/assets/5481718/8064968/8a68b35a-0e9b-11e5-8b38-f6f42d9cc9fc.png)

Featured courses would be a check box in the admin dashboard for courses under the edit option.

Only administrators should be able choose what courses would be "Featured" or not.

The "Other Courses" column on the right would only display non "featured" open courses. (Don't duplicate courses on both sides like the example picture)

**Comment by JKJensen** [comment]
There's currently a "Boom! Something broke" error when I try to feature a course.

![cannotcreatefeaturedcourse](https://cloud.githubusercontent.com/assets/5481718/9529188/33c7760e-4cb6-11e5-93a9-b1666085063b.gif)

Text from that error:

```


Execution exception[[NoSuchElementException: key not found: name]]

play.api.Application$class.handleError(Application.scala:289)
play.api.DefaultApplication.handleError(Application.scala:383)
play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$handleAction$1$4$$anonfun$apply$28.apply(PlayDefaultUpstreamHandler.scala:391)
play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$handleAction$1$4$$anonfun$apply$28.apply(PlayDefaultUpstreamHandler.scala:391)
scala.Option.map(Option.scala:145)
play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$handleAction$1$4.apply(PlayDefaultUpstreamHandler.scala:391)
play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$handleAction$1$4.apply(PlayDefaultUpstreamHandler.scala:386)
play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113)
play.api.libs.concurrent.PlayPromise$$anonfun$extend1$1.apply(Promise.scala:113)
play.api.libs.concurrent.PlayPromise$$anonfun$extend$1$$anonfun$apply$1.apply(Promise.scala:104)
scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
java.lang.Thread.run(Thread.java:745)


```

I was trying to feature the following course:
http://sartre3.byu.edu:9006/course/85

**Comment by gliese1337** [comment]
That is odd. It seems to be working now. Go ahead and re-open if you run into the error again, but I can't replicate it at the moment.
