### ISSUE TITLE
Remove the "Request Course Access" splash page when joining an open course, add a "join course" button to open courses.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#526]
Right now when a user browses through open courses they cannot view any content in a course unless they "join" it.

![changeitsousersdontneedtorequestpermissiontojoinanopencourse](https://cloud.githubusercontent.com/assets/5481718/8065387/5f646b1a-0e9e-11e5-9fb7-14eafe570c9c.gif)

Users should be able to go through and view public courses without joining them. However, there is a still a "Join this Course" button left in the Header.

![addajointhiscoursebuton](https://cloud.githubusercontent.com/assets/5481718/8065656/043c1d30-0ea0-11e5-91dd-6e30c8b69b4d.png)

Once they click that button their picture shows up and they are a listed member of the course.

**Comment by shyatt** [comment]
This is still the case, is it not? Did we decide this is how we want it to
work (that they have to join the course to see the content)?

On Fri, Jun 19, 2015 at 5:28 PM, Santiago Verdu <notifications@github.com>
wrote:

> Closed #526 <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/526>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/526#event-335711143>
> .
>



-- 
Shari Hyatt

**Comment by verdude** [comment]
On the beta site, if you go to a course that you do not belong to, then it will take you directly to that course and there will be a button that you can click on to join the course.

   - open courses completely ignore the request page (you are also not automatically added to them)
   - going to a closed course will redirect you to the request page (if you are not an admin or part of the course)

**Comment by shyatt** [comment]
Okay, I understand. So just so I am not mistaken, you fix it on the beta
site and then push it to the production site later? Is that correct?

On Mon, Jun 22, 2015 at 2:35 PM, Santiago Verdu <notifications@github.com>
wrote:

> On the beta site, if you go to a course that you do not belong to, then it
> will take you directly to that course and there will be a button that you
> can click on to join the course.
>
>    - open courses completely ignore the request page (you are also not
>    automatically added to them)
>    - going to a closed course will redirect you to the request page (if
>    you are not an admin or part of the course)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/526#issuecomment-114255040>
> .
>



-- 
Shari Hyatt

**Comment by verdude** [comment]
Yes
