### ISSUE TITLE
Adding a Thumbnail based on location in video compresses the image for 16x9 video

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#529]
If a user tries to select a thumbnail based on the current point in the video, and the aspect ratio is 16x9, the thumbnail that is created is compressed into a square aspect ratio.

![makeathumbnailstretches16x9images](https://cloud.githubusercontent.com/assets/5481718/8070323/aae8f62c-0ebd-11e5-9a66-ea21b1aba889.gif)

It should bring up an option for the user to crop the photo themselves. If that's too much work, only use the center of the video and make a thumbnail from that.

**Comment by gliese1337** [comment]
This is odd, because there is in fact correct-looking code that's intended to maintain the correct aspect ratio when resizing thumbnails in ImageTools.scaleImage()
