### ISSUE TITLE
More Specific Error Messages when user accesses private content

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#534]
When a user tries to access private content right now it shows up as "Oh Snap! You cannot do that."

In that situation the error message should be: "This content was marked as private by the owner."

**Comment by gliese1337** [comment]
A better solution is that they just shouldn't be able to see content at all if they aren't allowed to access it.

**Comment by gliese1337** [comment]
I kinda accidentally already fixed this. Sorry, Jeff!
