### ISSUE TITLE
We need a smaller font when the number of subtitle tracks on a single video reaches above fourteen.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#535]
![needasmallerfont](https://cloud.githubusercontent.com/assets/5481718/8133359/24a88864-10e5-11e5-8021-3abf20b61400.gif)
https://ayamel.byu.edu/content/2447

The Crash Course Series on Youtube has an astonishing 18 languages it has subtitles tracks available. However, Ayamel will only display 17. 

There a two ways around this: Make the font smaller when the number of subtitle tracks reaches above 14. Or after 14 tracks, enable two columns to show up when selecting a caption.

**Comment by JKJensen** [comment]
Okay, it looks like the number of translated languages drops down to ten in later videos, so this isn't that urgent of a problem.

**Comment by gliese1337** [comment]
Just to clarify: this is a smaller font / multiple columns for the subtitle track menu, not for subtitles rendered over the video, right?

**Comment by JKJensen** [comment]
Yes, just the "picking a subtitle track" menu.

**Comment by gliese1337** [comment]
Fixed by re-arranging into two columns when the menu gets too long.

**Comment by JKJensen** [comment]
Did this issue fix ever get pushed to the beta site? I'm still running into the same problem on this video:
http://sartre3.byu.edu:9006/content/436

**Comment by gliese1337** [comment]
Somehow it got pushed to master while getting left off of develop. Probably my bad. I've fixed it now.
