### ISSUE TITLE
Deleting Announcements on Homepage

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#538]
It would be nice if there were a way to delete an announcement after you have made it. Just in case you want to change any of the details or just get rid of it.

**Comment by verdude** [comment]
Do we want to have a way to edit announcements or just be able to delete them?

**Comment by schyatt** [comment]
On the home page on the beta site, on the announcements there is a trash can icon so the user can delete announcements that they have posted. This icon does not work. The announcement is not deleted after you push on it. 
![delete](https://cloud.githubusercontent.com/assets/10120523/9361052/edaad040-4656-11e5-9ba4-14ab3fc51dc7.gif)

It does, however, work from the course page.
![works](https://cloud.githubusercontent.com/assets/10120523/9361104/2618e048-4657-11e5-9969-4fc9a70462e9.gif)
