### ISSUE TITLE
When User Makes a Suggestion, it doesn't show the text they entered on the Admin Feedback Tab

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#544]
I am user 318. I made a suggestion (Testing 123), but when I clicked on the feedback tab (as an admin), it just showed up as undefined. Also, it puts the most recent ones on the bottom of the list, which seems kind of counter intuitive 
![17f645e1542a2eba2e2d4bf30d4d7c54](https://cloud.githubusercontent.com/assets/10120523/8195597/19fd1ef2-1441-11e5-8f81-76e8d0363cd0.gif)

**Comment by gliese1337** [comment]
Wow. I did not even know this feature existed. Does anybody really use this? Have we ever actually checked the suggestion list? Could we maybe just get rid of it entirely, and then that's one less thing that can break?

**Comment by gliese1337** [comment]
Issue obviated by removing the site-internal feedback system. User feedback now goes directly to the lab e-mail.
