### ISSUE TITLE
Admin Cannot Delete a User

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#545]
I tried to delete a user from Ayamel and could not. I waited about a minute, but nothing ever notified me that the user had been deleted.
User #1910 
![delete](https://cloud.githubusercontent.com/assets/10120523/8195736/36642a12-1442-11e5-94a1-7ef850038730.gif)

**Comment by gliese1337** [comment]
Probably the same issue as #546. It looks like an issue with the JQuery dialog boxes.
