### ISSUE TITLE
Admin Cannot Notify a User

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#546]
I am unable to notify a user on the admin dashboard.
![notify](https://cloud.githubusercontent.com/assets/10120523/8195824/cb7e6770-1442-11e5-8ce7-ca9ab60fe1b5.gif)

**Comment by gliese1337** [comment]
Probably the same issue as #545. It looks like an issue with the JQuery dialog boxes.
