### ISSUE TITLE
Admin Cannot see User Password

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#547]
As far as login information goes, I can see their username, but even if I go in and proxy them, I cannot see their password, even under their account settings.
![password](https://cloud.githubusercontent.com/assets/10120523/8195933/935f2a0e-1443-11e5-9bc7-f5e2861c050a.gif)

**Comment by gliese1337** [comment]
This is intentional. If you could, that would be a *major* security error. Users themselves cannot see their own passwords, because the server doesn't store them- we only store the one-way hash.
