### ISSUE TITLE
When Giving User Permissions, the default is Admin

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#548]
When an administrator gives a user permissions, the default is automatically admin. Maybe we should change it to something like create a course.
![default](https://cloud.githubusercontent.com/assets/10120523/8195981/09d90e7a-1444-11e5-9db6-0e0efe05eee4.gif)

**Comment by gliese1337** [comment]
The default was set as "admin" because that seemed the most useful account feature to be able to see at a glance, contrasted with everything else.

I've changed it to default to "Nothing selected".
