### ISSUE TITLE
Non-existent Caption Tracks Show Under Configuration

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#550]
Caption Tracks that do not exist under the caption track list are an option in configuration.
![track](https://cloud.githubusercontent.com/assets/10120523/8196504/e5e9799a-1449-11e5-8234-67388d4d6fe4.gif)

**Comment by verdude** [comment]
Fixed with #532. 6b8bd00ac913e1f0f4ee9e59e98d6e575e567df9
