### ISSUE TITLE
Cannot export words from my word list to Quizlet

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#554]
Cannot export words from my word list to Quizlet
![quizlet](https://cloud.githubusercontent.com/assets/10120523/8291760/c1f88f82-18e8-11e5-8be8-6a3765132432.gif)

**Comment by gliese1337** [comment]
Near as I can tell, that's Quizlet's problem, not ours.

**Comment by schyatt** [comment]
This is still an issue on the main site, but not the beta site (which asks you to give permission (see pics). 
Main site:
![quizlet](https://cloud.githubusercontent.com/assets/10120523/9585843/8326a684-4fd6-11e5-9081-e445f6277d30.PNG)

Beta site:
![quizlet 1](https://cloud.githubusercontent.com/assets/10120523/9585832/79500fb0-4fd6-11e5-971f-beb17a07733c.PNG)
