### ISSUE TITLE
Check for existing database records before inserting in SQLSavable trait

### ISSUE THREAD

**Issue by verdude** [BYU-ARCLITE/Ayamel-Examples#555]
Right now the insert function will simply enter a new record into a table when called. It would be good to add a check so that it doesn't create duplicate entries.

Prior to implementing this check for existing records, we need to confirm that the models using this function do not make use of duplicate database entries.

**Comment by gliese1337** [comment]
I think the proper way to go about this is probably to move those checks into the database itself. We can specify individual tables as not allowing duplicate entries, and then just allow the SQLSavable trait can just throw database errors if you try to create duplicates in models that don't support them.
