### ISSUE TITLE
Loading "My Content" Page

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#559]
Loading the "My Content" Page is interminably long, suggesting that the server is doing a linear search of all content to prepare the display! There must be a way to improve this search and display using a MySQL query, perhaps to a temporary table and then displaying those results.

**Comment by gliese1337** [comment]
Nope. It's doing it in a single SQL query. Specifically, this one:

"select * from content join contentOwnership on content.id = contentOwnership.contentId where contentOwnership.userId = {userId}"

This could be more efficient if we eliminated the indirection of the "contentOwnership" join table, whose only purpose is to allow multiple people to own the same content, a use-case which we never use. But that's a major project that goes way beyond just loading the "My Content" page.
