### ISSUE TITLE
When in the help page, the my courses and user icon don't work

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#563]
When in the help page, the "my courses" and "user" icon don't work. You click on them and it doesn't do anything. The "Home", "Help", and "My Content" icons work fine. 
![help](https://cloud.githubusercontent.com/assets/10120523/8339288/94bc82e4-1a73-11e5-8c5f-008c25098ae7.gif)

**Comment by verdude** [comment]
The fix will manifest itself when the production site is updated to the latest version. f40cd62cdbf7dc2a73bf0c820e342d88d99e7161
