### ISSUE TITLE
When you try to quit the annotation editor, it goes back to the launch annotation editor screen

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#564]
When you try to quit the annotation editor by selecting quit, it goes back to the launch annotation editor screen instead of to the player/ video.

**Comment by verdude** [comment]
By annotation editor screen, do you mean this? :

![image](https://cloud.githubusercontent.com/assets/5685655/8366875/3bccde34-1b56-11e5-8546-f5c04e40052c.png)

I haven't been able to reproduce this error. How are you getting to the annotation editor?

**Comment by shyatt** [comment]
Yes that is the annotation editor screen. I was using the lab mac computer,
and found that I only ran into this error if I was logged in as Arclite
User and didn't get the error if I was logged on as a different user. I
tried clearing the browsing cache, but still got the error with the Arclite
User. I don't really know what that means. Maybe I didn't clear the cache
correctly or something. Are you coming to the lab today?

On Thu, Jun 25, 2015 at 4:23 PM, Santiago Verdu <notifications@github.com>
wrote:

> By annotation editor screen, do you mean this? :
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5685655/8366875/3bccde34-1b56-11e5-8546-f5c04e40052c.png>
>
> I haven't been able to reproduce this error. How are you getting to the
> annotation editor?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/564#issuecomment-115417989>
> .
>



-- 
Shari Hyatt

**Comment by verdude** [comment]
Yea, I'll be there around two or a little later
