### ISSUE TITLE
The volume bar covers up other buttons when Ayamel Player shrinks

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#565]
The volume bar covers up other buttons when Ayamel Player shrinks
![volume](https://cloud.githubusercontent.com/assets/10120523/8342248/f462cf1e-1a87-11e5-8fa4-6da1f94340fa.png)

**Comment by gliese1337** [comment]
Can't replicate. Try clearing your cache; this issue was resolved several months ago.
Also *please* include URLs to the offending pages!
