### ISSUE TITLE
When you disable an annotation track, it no longer shows up in the annotation editor so you can edit it

### ISSUE THREAD

**Issue by shyatt** [BYU-ARCLITE/Ayamel-Examples#566]
When you disable an annotation track, it no longer shows up in the annotation editor so you can edit it. It only shows the tracks that are enabled.
![edit](https://cloud.githubusercontent.com/assets/10120523/8342458/75773b20-1a89-11e5-98d4-6d42241d6499.png)

**Comment by verdude** [comment]
Works on the beta site. It'll get to the main site when we are ready to push the changes.
