### ISSUE TITLE
Trying to make an announcement and got the "something broke" message.

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#568]
I tried to make an announcement and got the "something broke" message:
![broke](https://cloud.githubusercontent.com/assets/10120523/8381786/1f59d726-1beb-11e5-8a1d-ecd0b2cbeabb.gif)

Then when I pushed save after inserting my message, I got this screen:
![action](https://cloud.githubusercontent.com/assets/10120523/8381813/596d8340-1beb-11e5-9f8c-283231c9b06a.gif)

**Comment by gliese1337** [comment]
Live site or beta site? Please provide a URL so we can try to replicate this.

**Comment by gliese1337** [comment]
The feedback form on the error page should be fixed now, so I'm reverting this back to an issue about getting an error while trying to make an announcement.

**Comment by schyatt** [comment]
Sorry...
Here is the url:
https://ayamel.byu.edu/course/311/announce
https://ayamel.byu.edu/course/311
Live site
Here is the message:
All current members of this course now have the ability to add content,
make announcements, and edit the content in this course. Please contribute
and make this open course even more awesome. Just make sure all the content
is public and not private.
Check out this help page to see how to contribute to Ayamel.
https://ayamel.byu.edu/help/74

On Fri, Jun 26, 2015 at 3:46 PM, Logan Kearsley <notifications@github.com>
wrote:

> Live site or beta site? Please provide a URL so we can try to replicate
> this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/568#issuecomment-115898995>
> .
>



-- 
Shari Hyatt
