### ISSUE TITLE
Automatically have captions come on when you turn on annotations

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#572]
It would be nice if the captions would automatically turn on when you turn on an annotation track. 
![annotations](https://cloud.githubusercontent.com/assets/10120523/8386922/9e7a0b04-1c11-11e5-8d2e-af6ccdaaade9.gif)

**Comment by gliese1337** [comment]
We'd just have to undo it later, since annotations ought to also show up in transcripts. See #179
