### ISSUE TITLE
Be able to add or remove members of a course via LMS (like Learning Suite)

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#575]
Learning Suite (As well as other Learning Management Systems) should have the ability to add or remove the members of an Ayamel course.

This includes checking if a student is in a course and adding him or her to the course. If they are already in the course, do not add them twice.

**Comment by gliese1337** [comment]
While we would have to do some work on our side to accommodate it, this seems like an issue for Learning Suite and Canvas, more than it is an issue for Ayamel. I am not aware of any standard API for allowing an LMS to manage user accounts on an external system, so I'm going to close this as "wontfix" until/unless there seems to be a viable way forward.
