### ISSUE TITLE
Notification to Admins when Someone Requests Additional Permissions

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#576]
There should be some sort of notification to admins when someone requests additional permissions. The only way you currently know is by going to the admin dashboard, selecting the users tab and then choosing the permission requests. I could see requests going unanswered for a long time because I don't know about you, but I hardly look at the permission requests tab.
url:  https://ayamel.byu.edu/admin/permission
![permissions](https://cloud.githubusercontent.com/assets/10120523/8435604/828c014e-1f0f-11e5-924d-908253e9e907.gif)

**Comment by gliese1337** [comment]
This uses the same system as e-mailing users with any other notification, and so ought to fix itself along with #560 .
