### ISSUE TITLE
Cannot See Restricted Content Even With the Permissions to do so

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#577]
For a user that has the permissions to view restricted content, they have no way of doing so. There is nowhere that I know of for them to access the restricted content (which makes the loosely restricted content setting almost null). 
![null](https://cloud.githubusercontent.com/assets/10120523/8435738/3d773c26-1f10-11e5-8390-45639f25e896.gif)

**Comment by verdude** [comment]
Perhaps the way they are meant view restricted content is through courses to which the content has been added.

Also, the content search functionality has been put on the wait list. After the search option is made, then they will be able to view the restricted content.

**Comment by JKJensen** [comment]
This should be tested once the search feature is completed.
