### ISSUE TITLE
Slow down feature of Ayamel Player disappears when we add videos with the brightcove://videoID

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#579]
The slow down feature on the Ayamel Player disappears when we add videos with the brightcove://videoID

url:https://ayamel.byu.edu/course/334/content/1204
![slowdown](https://cloud.githubusercontent.com/assets/10120523/8438614/3898e5ba-1f24-11e5-81ac-85cbe2257afb.gif)

**Comment by schyatt** [comment]
But when you add it with the .mp4 url from brightcove:  https://lds-a.akamaihd.net/pmd/1126213333001/2015/06/1126213333001_4314393747001_4036669868001.mp4
It works just fine:
url: https://ayamel.byu.edu/content/1204
![slow](https://cloud.githubusercontent.com/assets/10120523/8438968/469c5a5a-1f26-11e5-95c2-66931ef6f2b3.gif)

**Comment by gliese1337** [comment]
Fixed.
