### ISSUE TITLE
Batch Upload on Ayamel straight to the Course you want it in doesn't work

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#581]
I tried to batch upload some Arabic Videos to the Arabic Public Content Course and it did not work. It uploaded it to my content, so the batch upload works, but it didn't put it in the course.
url:  https://ayamel.byu.edu/content/create/batch/349

![batch](https://cloud.githubusercontent.com/assets/10120523/8443842/865f6c06-1f47-11e5-9002-25806dd73183.gif)

This is showing it in my content:
![syrian](https://cloud.githubusercontent.com/assets/10120523/8443845/8bc6b424-1f47-11e5-8cfb-c63fe97b2317.gif)

**Comment by schyatt** [comment]
I did this wrong, so probably not a bug.

**Comment by johnlarson** [comment]
Fixed it on the develop branch!
