### ISSUE TITLE
Subtitle Tracks don't show up after uploading a third track

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#582]
I uploaded three subtitle tracks for a movie. When I had two, it worked just fine. As soon as I uploaded the third, it said there were no caption tracks available even though all were enabled. I deleted the third track, and then the two worked again.
url:  https://ayamel.byu.edu/course/311/content/2506
![three sub](https://cloud.githubusercontent.com/assets/10120523/8459089/043e6b46-1fd8-11e5-8a2c-a2299b0ad24a.gif)
![two sub](https://cloud.githubusercontent.com/assets/10120523/8459090/046d77a6-1fd8-11e5-9a4c-3f4f6452e6b9.gif)

**Comment by schyatt** [comment]
Also, the transcript disappears after adding the third track and you can't access any of the tracks in captionaider.
The third track I uploaded was the Spanish one.

**Comment by schyatt** [comment]
I added three subtitle tracks to this video last week, and it works just fine.
https://ayamel.byu.edu/course/311/content/2436

**Comment by schyatt** [comment]
Also, when I disable the Spanish track, the other two work again. When I have the the Spanish track enabled, but disable one of the other languages, it stops working again. So it must have something to do with that specific Spanish track. But it still doesn't make sense to me that because one track is bad, all the tracks don't work...

**Comment by gliese1337** [comment]
The spanish track doesn't seem to be there now, which makes this difficult to investigate. Reopen if you can replicate the issue on the beta site.

**Comment by schyatt** [comment]
Here is the link on the Beta site:
http://sartre3.byu.edu:9006/content/440

It is easy to see that the reason the Spanish Track doesn't work is because
it is a plain text file, but it doesn't make sense that the other two
subtitle tracks no longer work or even show up (they are actual .srt files)

On Tue, Jul 14, 2015 at 3:54 PM, Logan Kearsley <notifications@github.com>
wrote:

> Closed #582 <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/582>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/582#event-355857456>
> .
>



-- 
Shari Hyatt

**Comment by gliese1337** [comment]
Fixed!
