### ISSUE TITLE
Mac- While on "Help" page drop down menu for "My Courses" does not display

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#591]
While a user is on the help page ( https://ayamel.byu.edu/help ), if they click on "My Courses" the full drop down menu of their courses does not display.
![cantclickonmycoursesfromhelppage](https://cloud.githubusercontent.com/assets/5481718/8580344/6797772e-2577-11e5-835d-56de332edd37.gif)

**Comment by verdude** [comment]
Fixed on beta site.
