### ISSUE TITLE
Video Window on Playback Not filling Available Browser Tab Space

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#593]
I start up M Batignole at this URL on the Beta Site:

http://sartre3.byu.edu:9006/content/25

and see this layout:

![image](https://cloud.githubusercontent.com/assets/7268293/8634651/2ca7619e-27be-11e5-8c86-5dc116faed16.png)

**Comment by gliese1337** [comment]
This is a problem with the underlying player plugin being used. That particular copy of M. Batignole points directly at the m3u8 HLS manifest file that incidentally happens to be hosted on Brightcove's CDN. Thus, it is using the not-quite-ready-for-primetime HLS player. Other videos shouldn't have a problem, but add another comment if you find some that do. It's always possible that there are similar problems with other plugins.
