### ISSUE TITLE
Auto Definition doesn't work when you set the def. language

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#595]
On the beta site, auto definition doesn't work when you get a def. in one language and then change the def. language and try to get a definition. 
This was tested on the beta site:
http://sartre3.byu.edu:9006/course/34/content/354
![def](https://cloud.githubusercontent.com/assets/10120523/8678915/ad8b718a-2a14-11e5-8ff1-808ab289da16.gif)

**Comment by schyatt** [comment]
Or maybe it has just stopped working completely after you specify the definition language:
In this one, I first selected the definition language and then tried to get a definition, but nothing happened, so I tried a couple of different languages and didn't get any definitions. 
![def1](https://cloud.githubusercontent.com/assets/10120523/8679015/4a2236f0-2a15-11e5-9cef-edde114d369f.gif)

**Comment by gliese1337** [comment]
Somehow, the Translator target language is getting set to "undefined".
