### ISSUE TITLE
Auto adjust selected cue up to yellow progress line

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#596]
It would be really nice if in captionaider you had the tool to auto adjust a cue up to where the yellow progress line is. It would be a lot faster than dragging it to that point, and it would also make it more accurate when you are trying to adjust multiple subtitle tracks. 
![cue](https://cloud.githubusercontent.com/assets/10120523/8729451/935f8306-2ba8-11e5-8ff0-caa3444fe483.gif)

**Comment by gliese1337** [comment]
Feature added!

**Comment by schyatt** [comment]
How do you perform this new feature?

On Thu, Jul 16, 2015 at 7:18 PM, Logan Kearsley <notifications@github.com>
wrote:

> Closed #596 <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/596>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/596#event-358114270>
> .
>



-- 
Shari Hyatt

**Comment by gliese1337** [comment]
Haven't had a chance to deploy the updates yet, but it shows up as a context menu option (actually, several context menu options, depending on whether you want to move the start or end time and whether the current time is during, before, or after the current timespan of the segment in question).
