### ISSUE TITLE
When a user accesses "set media source" it should say what the current source of the video is.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#601]
On a content page users can edit the media source by going to Video-> Edit -> Set Media source.

![screenshot 2015-08-06 13 42 58](https://cloud.githubusercontent.com/assets/5481718/9121691/2984f08e-3c41-11e5-9427-b343845852bf.png)

On this page it should show the url where the current content is being displayed from.

**Comment by gliese1337** [comment]
Temporarily fixed. As a note, though, this feature ought to be deprecated and removed in favor of a comprehensive resource-editing system.
