### ISSUE TITLE
Unable to call annotations on the Beta site

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#605]
I am unable to save annotation edits on the Beta site.
![1](https://cloud.githubusercontent.com/assets/10120523/9185879/020b8ff6-3f7d-11e5-8835-151d80c3db84.gif)
url for video:  http://sartre3.byu.edu:9006/course/21/content/84

**Comment by schyatt** [comment]
I am also unable to save changes made in captionaider.
![2](https://cloud.githubusercontent.com/assets/10120523/9264691/73056ffe-41e6-11e5-8306-8e911146212a.PNG)

**Comment by schyatt** [comment]
This is a problematic bug because we cannot test annotations on the beta site because we cannot create any to test.

**Comment by verdude** [comment]
I fixed this by changing the beta site keys to the keys that I had saved on my personal configuration file. The strange thing is that the production site is able to save documents using the keys that do not work on the beta site.

**Comment by schyatt** [comment]
URL for the video: http://sartre3.byu.edu:9006/content/532
The annotations are still not saving. First issue:  I save the annotations, it says it is saved, and then it gives me a warning when I quit the editor that I have unsaved changes.
![save](https://cloud.githubusercontent.com/assets/10120523/9363171/1319a710-4662-11e5-92c0-461f8d09eb25.gif)
Second issue:  When I go to enable the annotations, they have three of the same annotation file:
![three](https://cloud.githubusercontent.com/assets/10120523/9363201/3c856a08-4662-11e5-909d-abe14962bb58.PNG)
Third issue:  The annotations are not showing up when I play the video (I have turned them on and enabled them. I also cleared my browsing data). 
![annotations](https://cloud.githubusercontent.com/assets/10120523/9363224/64154e08-4662-11e5-90c9-8d055380f18b.PNG)
When I go back to look at the annotation editor, it shows that the annotations I have created are there and saved.
![annotations1](https://cloud.githubusercontent.com/assets/10120523/9363239/7cbbf9b6-4662-11e5-819c-15cfdd1e4b8b.PNG)

**Comment by daganrh** [comment]
The annotations are being saved, (if you make a new set of annotations and save it you can go back and find them again) the problems seems to be that the annotation files are not being read correctly, or something like that.
