### ISSUE TITLE
High Priority: Enable multiple line breaks for descriptions.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#607]
Right now the descriptions for videos are limited to only one line with no way of enabling multiple line breaks.
![enablemultiplelinebreaks](https://cloud.githubusercontent.com/assets/5481718/9186226/077c946e-3f80-11e5-8446-c7e0b3b79a29.gif)

Line breaks in the description editing field should create line breaks in the video description as well.

**Comment by schyatt** [comment]
At this point, you can put a line break in the "Edit metadata" window, but it doesn't show up as a line break under the video player. It just has extra spaces between the sentences. 
![enter](https://cloud.githubusercontent.com/assets/10120523/9445854/8f0fc9f2-4a4b-11e5-8db7-8a27be13132c.PNG)
