### ISSUE TITLE
Firefox: Unable to change the speed of Youtube video

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#612]
On Safari and Chrome the user is able to adjust the speed of the audio, however on firefox clicking the knob to change the speed does not move anything. The section is entirely unresponsive.

Tested on this Youtube video in Firefox:
http://sartre3.byu.edu:9006/course/86/content/449

**Comment by gliese1337** [comment]
This is because YouTube doesn't allow adjusting the speed of the video in Firefox.
Ideally, we would hide the rate slider in this case, but we can't tell whether or not it will be useful until after the player is already loaded, which makes that difficult.
