### ISSUE TITLE
Beta Site: cannot upload an mp4

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#616]
I tried to upload a short .mp4 and got an error.
![test](https://cloud.githubusercontent.com/assets/10120523/9258623/cf484016-41b9-11e5-82bd-b39346c07b48.gif)

**Comment by JKJensen** [comment]
This is part of #608. A lot of stuff can't be uploaded right now.

**Comment by schyatt** [comment]
Bug #608 has been closed, but there are still issues uploading an mp4. The first is that when you upload it, the video doesn't fit the player. It only fills the top corner. The other issue is that when you play the video, the video doesn't play, but the audio from the video does (in this particular video, I did a screencast and kept switching tabs, but in the video on Ayamel, it doesn't show me switching the tabs). Moreover, when it is uploaded on Ayamel, it redirects me to a screen, but it doesn't give me a content number, but instead goes to this url :http://sartre3.byu.edu:9006/content/create/file
When I click on My Content, it did upload to this url: http://sartre3.byu.edu:9006/content/545

**Comment by schyatt** [comment]
On firefox, you still get the issue where it redirects you to this url: http://sartre3.byu.edu:9006/content/create/file
once you upload the video, but the video plays and fills the whole screen.
![firefox](https://cloud.githubusercontent.com/assets/10120523/9361788/68bccf38-465a-11e5-857a-105c29825ba6.PNG)

**Comment by schyatt** [comment]
Also, when viewing the videos on Firefox, they work fine (you can hear the sound and see the video progress), but viewing them on chrome, they do not (you hear the sound, but don't see the video progress).
![play](https://cloud.githubusercontent.com/assets/10120523/9361949/32243c08-465b-11e5-81e6-33f699d42688.gif)

**Comment by JKJensen** [comment]
The problem that occurs only in Firefox on Windows occurs in all three browsers on Mac.

Uploading a <20MB file will result in none of the video displaying but the audio still occurring.
Though this might be a low priority fix because few people upload <20MB video files.

![soundbutnovideo](https://cloud.githubusercontent.com/assets/5481718/9363178/2108da94-4662-11e5-90e8-271af45f8dc7.gif)

**Comment by gliese1337** [comment]
Figured out a workaround to display the proper URL after adding content. The video playback problems were caused by THEOPlayer, so I've just removed THEOPlayer from the system.
