### ISSUE TITLE
Ayamel Beta site: Clicking on a spot in the transcript to go to that point of the video does not change video location

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#617]
The Ayamel player does not change the spot in which the video is playing when a cue in the transcript is clicked.
![transcriptclickingnotworking](https://cloud.githubusercontent.com/assets/5481718/9260067/a6093134-41c2-11e5-9a47-03554dda1565.gif)

It should work like on the main site right now, or like how Youtube's transcript behaves on click.
![howyoutubehandlestranscript](https://cloud.githubusercontent.com/assets/5481718/9260180/675ba088-41c3-11e5-8ecb-3875f5696eb8.gif)

**Comment by schyatt** [comment]
same bug as #606

**Comment by JKJensen** [comment]
This works now!
