### ISSUE TITLE
Fullscreen pullout tab for the transcripts has an unintentional "night mode"

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#620]
Instead of the background being white for the transcripts, they are black. Which actually makes a really nice looking "night mode."

![unintentionalnightmode](https://cloud.githubusercontent.com/assets/5481718/9261981/e94cab40-41ce-11e5-9747-37243edc4e4a.gif)

But this should have a white background in Firefox instead of black.

**Comment by dro248** [comment]
@johnlarson: Didn't you say that you fixed this a few days ago?

**Comment by johnlarson** [comment]
Oh, yeah! I did; I'll close it.
