### ISSUE TITLE
Beta Site: Existing users do not have the option to change their password

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#621]
Existing users do not have the option to change their password. 
![password](https://cloud.githubusercontent.com/assets/10120523/9263700/8d4ba9dc-41dc-11e5-9d49-54d77a026725.gif)
When I created a new account, however, I had the option
![new](https://cloud.githubusercontent.com/assets/10120523/9263711/a3108490-41dc-11e5-8ece-747ae988931d.gif)
I proxied a couple of existing users with extra permissions to see if this was the case for them as well, and it was.
Other users, however, don't even have a user icon, or any of the options available when you click on them (I think Jeff made a bug about this):
![1](https://cloud.githubusercontent.com/assets/10120523/9263768/2b209744-41dd-11e5-9010-5b24a423e70b.gif)

**Comment by JKJensen** [comment]
Doesn't work by design for BYU logins or Google logins.
