### ISSUE TITLE
Empty space in full screen mode

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#622]
There is blank space when you expand the video to full screen mode.
![full screen](https://cloud.githubusercontent.com/assets/10120523/9263937/d99660d2-41de-11e5-997b-d19fbabd2b57.gif)

**Comment by gliese1337** [comment]
Possibly related to #610

**Comment by gliese1337** [comment]
@schyatt Can we get a URL to replicate this?

**Comment by schyatt** [comment]
http://sartre3.byu.edu:9006/content/440
sorry...

**Comment by schyatt** [comment]
This is an issue on the production site as well, though not as bad. 
![blank](https://cloud.githubusercontent.com/assets/10120523/9554892/856730c8-4d86-11e5-88fe-05d9596f0697.gif)

**Comment by schyatt** [comment]
How bad this issue is depends on the aspect ratio.
![blank](https://cloud.githubusercontent.com/assets/10120523/9555041/c7243064-4d87-11e5-92da-d79f06af07d3.gif)

**Comment by gliese1337** [comment]
This is super weird. It seems to be working fine in Firefox, but the resizing fails in Chrome.
