### ISSUE TITLE
Dictionary service doesn't always give a translation and a definition in the desired translation language.

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#623]
I tried to change the language to translate words to to Albanian. I did not get a translation in Albanian, but a definition in French.
![translate](https://cloud.githubusercontent.com/assets/10120523/9264180/918b4d3c-41e0-11e5-8b34-484e57f4a13e.gif)

**Comment by schyatt** [comment]
Here is the URL:  http://sartre3.byu.edu:9006/content/440
Time: 10:44

**Comment by gliese1337** [comment]
Ayamel seems to be operating correctly. This should be tracked in the DictionaryLookup repo, on this issue: https://github.com/BYU-ARCLITE/DictionaryLookup/issues/1
