### ISSUE TITLE
Giving a student the "View Student Data and Analytics" permission enables them to add ALL permissions to themselves.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#625]
If a teacher gives a student the permission to "View Student Data and Analytics" then that student has the ability to give themselves the rest of the permissions.

So here is what the teacher does:
![viewstudentpermission](https://cloud.githubusercontent.com/assets/5481718/9282331/db79416c-4288-11e5-81aa-c8c37c3459d4.gif)

And here is how the student adds more permissions:
![viewstudents](https://cloud.githubusercontent.com/assets/5481718/9282336/e774aa1a-4288-11e5-930d-3116e2826afd.gif)

![addallthepermissions](https://cloud.githubusercontent.com/assets/5481718/9282345/01a3a080-4289-11e5-948d-ac8fe2384c82.gif)

Possible solutions:
1. Change "View Student Data and Analytics" to "All Permissions" (or maybe "All Teacher Permissions") and default these users to have all permissions.
2. Give the student the "View Student Data and Analytics" permission, but remove their ability to edit the "Select Permissions" and give other students and themselves more permissions.

**Comment by johnlarson** [comment]
I looked at this, and it looks like when the teacher selects "View Student Data and Analytics" and gives that permission to a course member, it gives that course member the "teacher" permission. I haven't looked in the controllers, but the views don't include a student viewing window unless the user has the "teacher" permission. Should not all teachers be allowed to do this? Or should there be a separate permission for viewing student data? Or is there something other way this should be done? Or should we just do Jeff's first solution for now for the sake of getting things done quickly?

**Comment by JKJensen** [comment]
I'd say change the label of "View Student Data and Analytics" to "All Teacher Permissions." That sounds easier to implement and is the most straightforward way to express the permission they are getting.
