### ISSUE TITLE
Mac-Safari: Brightcove videos on Safari have a blur at the start of the video sometimes.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#626]
Here is one of the videos that is having the problem: http://sartre3.byu.edu:9006/content/503
For some reason at the 15 or so second mark or so the blurriness of the Safari version corrects itself. But if you look at Firefox and Safari side by side Firefox has slightly superior quality.

However, this Brightcove video seems to be working on Safari at the beginning: http://sartre3.byu.edu:9006/content/501

**Comment by gliese1337** [comment]
This is an issue with Brightcove's player and how it selects stream qualities. There's no clear path forward for anything we could do to fix it.
