### ISSUE TITLE
Beta Site: Cannot save subtitles to disk with Safari (Mac)

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#629]
I cannot save subtitles to my computer with Safari. When I try, nothing happens.
![save](https://cloud.githubusercontent.com/assets/10120523/9316392/025f6a8e-44f2-11e5-8b1c-f0d47331300b.gif)

I should have a save window pop open like this one:
![save1](https://cloud.githubusercontent.com/assets/10120523/9316463/6a0bcfba-44f2-11e5-9ba5-1b7e36c3aec0.gif)

Or it should start to download.
Url:  http://sartre3.byu.edu:9006/captionaider/354/0

**Comment by JKJensen** [comment]
It's working now.
![downloadsafarisubtitles](https://cloud.githubusercontent.com/assets/5481718/9369606/94d7706e-4687-11e5-9cec-9c4dffa22905.png)
