### ISSUE TITLE
When Captions are Deleted, Definitions Tab still shows up

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#630]
I had captions on this video, and had the transcript, definitions, and caption track enabled. Then, when I deleted the caption track, the transcript tab disappeared, but the definition tab remains with no way to make it go away.
![definitions](https://cloud.githubusercontent.com/assets/10120523/9316697/e283c5aa-44f3-11e5-9a16-4e6f17ee461c.gif)

**Comment by gliese1337** [comment]
This is subsumed in #699
