### ISSUE TITLE
Users are able to edit and delete resources which they do not own.

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#631]
When user makes changes to a cloned piece of content, it also changes the original piece of content.
In this case, I deleted the caption track on the cloned piece of content, and then caption track on the original piece of content was deleted as well. 
![clone](https://cloud.githubusercontent.com/assets/10120523/9316885/38752dfe-44f5-11e5-8243-9408f5b618ad.gif)
url for cloned content: http://sartre3.byu.edu:9006/content/542
url for original: http://sartre3.byu.edu:9006/course/34/content/354

**Comment by JKJensen** [comment]
Make it so that people that don't own resources don't have the ability to delete those resources.

**Comment by johnlarson** [comment]
So, should we set the user's permissions on the copy to match their permissions on the original?

**Comment by gliese1337** [comment]
No. All we need to do is *actually check* the permissions that people have on resources. https://github.com/BYU-ARCLITE/subtitle-timeline-editor/issues/10 is related.

**Comment by schyatt** [comment]
I just talked to Dr. Bush, and he said he was in the same boat as Jeff and I: thinking that cloning a piece of content meant you could make ANY changes to it without changing the original. He said we need to start a discussion about what "cloning" means and what it should do. I think we have kind of already started this discussion, but my end goal would be what Dr. Bush, Jeff, and I originally thought:  you clone a piece of content and you can make any changes you want to it without changing the original. Now that begs the question, how doable is that? Would we be clogging up the resource library by doing this?

**Comment by gliese1337** [comment]
It is already the case that you can make *any changes to what the student
sees* that you want without altering the original. That should be good
enough. There is absolutely no reason why anyone should ever *want* to make
changes that have no influence on what their content looks like, and yet
does impact other users of the same resource. Enabling that kind of
functionality would, indeed, result in pointless clutter in the resource
library for no visible benefit and some visible detriment- specifically,
that people would no longer be able to benefit from improvements to shared
resources, which is the whole *point* of the resource library.

**Comment by JKJensen** [comment]
For the record, this problem occurs both on the beta site and the main site. So I'm marking this as High Priority.

**Comment by gliese1337** [comment]
This should be resolved along with #695
