### ISSUE TITLE
Main site: Mac and PC: Brightcove videos will not play

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#638]
While on Mac in all three web browsers, Brightcove videos will not play. They will stay as a black screen and upon pressing play no video loads and the video player remains black.

![brightcovevideoswillnotplay](https://cloud.githubusercontent.com/assets/5481718/9555082/1e45cefc-4d88-11e5-8bd9-4fc0cd89a8d3.gif)

Here are a few videos to test with:
https://ayamel.byu.edu/content/2554
https://ayamel.byu.edu/content/2582

**Comment by schyatt** [comment]
This is happening on PC as well.
