### ISSUE TITLE
Views aren't being counted, but what exactly counts as a "view?"

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#642]
Right now on Ayamel it looks like the view counts for all videos were reset. None of my activities on these videos has increased the view count.

But that may not be a problem depending on what counts as a view. Is it a user visiting an Ayamel page? Clicking the play button? Or actually watching a video all the way through?

I've done all three of those, but I still can't seem to get a video to have more than zero views.

**Comment by verdude** [comment]
Activity Streams was counting the views but it was replaced by xApi. I thought I had left the code there, but I had removed it.

I just added it all back because I remember Dr. Bush saying we should keep it.
