### ISSUE TITLE
Main: Cannot directly upload video files

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#643]
Right now users that want to upload an under 20MB video file get a "Oh Snap! Failed to upload file" error.

![cannotuploadvideofiles](https://cloud.githubusercontent.com/assets/5481718/9557172/067b3dd4-4d97-11e5-9f8f-3c6f233581d1.gif)

**Comment by gliese1337** [comment]
Probably the same as #645
