### ISSUE TITLE
Cannot download stats to Excel spreadsheet

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#644]
You get an error when you try to download stats to an Excel spreadsheet on PC chrome:
![stats](https://cloud.githubusercontent.com/assets/10120523/9557506/c0579d22-4d99-11e5-997d-837c9cdd3fe0.gif)
url for video:  https://ayamel.byu.edu/content/2128

**Comment by DigitalProf** [comment]
I was able to download the Excel file, but the data for actions I had just taken were not present in the file.

**Comment by DigitalProf** [comment]
I just raised this to top priority. Data is not being recorded in the Activity Stream.

**Comment by DigitalProf** [comment]
Data is now being recorded. There is no problem in downloading the Excel file other than it takes what seems to be a long time (about one minute). I am closing this issue.
