### ISSUE TITLE
Cannot save/upload CaptionTracks or Annotations

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#645]
Whenever I try to upload caption tracks directly I get a save error. 
![errorwhilesavingerror](https://cloud.githubusercontent.com/assets/5481718/9558116/342aad02-4d9f-11e5-8231-185a124b704f.gif)
This also occurs while trying to save to the server in CaptionAider. Though the second dialogue says it does save. In the end it doesn't save.
![cannotsavesubtitles](https://cloud.githubusercontent.com/assets/5481718/9558119/3a41a362-4d9f-11e5-95f5-460e954a6274.gif)

**Comment by johnlarson** [comment]
Seems to work fine on the beta site. Has the new release been pushed yet?

**Comment by gliese1337** [comment]
This is probably the same bug as #639, but it will require more testing to confirm.
An "Access Denied" Amazon Client Exception is thrown when trying to save the uploaded file to S3. This may a result of the need to rotate our AWS keys, in which case it *may* just be coincidence that the problem cropped up at the same time as our latest master release.

**Comment by schyatt** [comment]
I am getting the same bugs on PC.

**Comment by schyatt** [comment]
I also cannot save any edits on annotations.

**Comment by DigitalProf** [comment]
I  just tried adding a track to a Russian song on YouTube and was unable to save the captions added from a TXT file. Here is the link to the video with CaptionAider: https://ayamel.byu.edu/captionaider/2719/0?

Here is the error I received:

![image](https://cloud.githubusercontent.com/assets/7268293/9640227/c84d04cc-516d-11e5-83df-9a14a53a3925.png)

Here are the messages on the console:

![image](https://cloud.githubusercontent.com/assets/7268293/9640243/e714cc14-516d-11e5-91df-9f5a6c2a7866.png)

**Comment by gliese1337** [comment]
Fixed. Someone ended up leaving the wrong AWS keys in the config file for the main site. I found the correct ones and restored them.
