### ISSUE TITLE
Main: The go to previous caption button is not visible on player

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#646]
The user cannot use the go to previous caption cue feature because the button to do so is not there.
URL:  https://ayamel.byu.edu/content/1905
![caption](https://cloud.githubusercontent.com/assets/10120523/9585592/3baced00-4fd5-11e5-8b58-67bf067d7a05.PNG)

**Comment by gliese1337** [comment]
@johnlarson this is a result of some of the plugins not having a "lastCaption: true" option set in their feature options. Dr. Bush asked me to ask you to look at that. You'll just need to go through each of the player plugins and make sure that they have that option added / turned on. For this particular video, it's the YouTube plugin, and the feature declarations start on line 250 of youtube.js

**Comment by johnlarson** [comment]
@gliese1337 I tried that with the youtube plugin, but it didn't work.

**Comment by gliese1337** [comment]
What exact edits did you make? Neither http://arclite.byu.edu/AyamelDev/Ayamel.js/js/plugins/youtube.js nor http://arclite.byu.edu/libs/Ayamel.js/js/plugins/youtube.js show the change, and I don't see any additional commits to the Ayamel.js repo, so I can't say what else might be going wrong if you've just been testing on your own localhost copy.

**Comment by johnlarson** [comment]
@gliese1337 I've made a new branch called 'lastCaption' and pushed it to GitHub.

**Comment by gliese1337** [comment]
@johnlarson I see what's going on. Set a breakpoint somewhere during the Player construction process, and step through to where the control bar is being built, and it ends up checking for support for each feature before rendering the relevant control element. You will note that https://github.com/BYU-ARCLITE/Ayamel.js/blob/lastcaption/js/MediaPlayer.js#L332 checks for the existence of function for the feature in question in a map of known features local to that source file. This mechanism is used to permit dynamic calculation of supported features that can't be known statically, but it does not have a proper fallback for features that are not dynamically calculated and thus ignores them even if they are specified in the plugin.

The simplest, most future-proof solution is just to add a new "lastCaption" function to the map in https://github.com/BYU-ARCLITE/Ayamel.js/blob/lastcaption/js/MediaPlayer.js#L4 *as well as* adding the feature option to all of the individual plugins.
