### ISSUE TITLE
Definitions Field not Using Available Space

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#648]
The size of the Definitions Field should be based on the height of the video window, not something else. It does currently change size and contents when the overall window is re-sized, but its size is not a function of the available space that is based on the video window.
![image](https://cloud.githubusercontent.com/assets/7268293/9610420/9e0c28aa-5096-11e5-8187-b1d09f829d2f.png)

**Comment by johnlarson** [comment]
Fixed as part of Issue #597.

**Comment by DigitalProf** [comment]
All,

Hallelujah and bravo for John and others who have helped him clear up this issue! The size of the transcript/definitions window has been a HUGE thorn in my side for months (years?) now. The re-engineering of the new player with which I know that Logan has been a major force is a big part of this. We knew that the problem was there, but we could not fix it until we had removed the transcript/definitions window from the Web page and placed it in the player.

Folks, this is a MAJOR accomplishment, so thanks to all!

I am sure I forgot the contributions of someone, but the good new is that EVERYONE will be able to come to the party we are going to have to celebrate our success. I have permission to throw a party with the money ($250) that is coming with the award we received.

So, let’s have some fun!

Cheers,

Prof Bush
