### ISSUE TITLE
Cannot Edit Captions on a New Track

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#649]
This could well be related to #644 and #647. While running Chrome on Windows 7, I created a track  and then could not display the track so I could proceed to enter content into the caption. 

![image](https://cloud.githubusercontent.com/assets/7268293/9640443/dfc113d6-516e-11e5-82cc-32976807a93a.png)

**Comment by gliese1337** [comment]
I was not able to replicate this. I just edited captions on a brand new track on the main site and it seemed to work fine.

**Comment by DigitalProf** [comment]
The issue seems to occur if a cue is added at the same spot where the play cursor is located. In that case it is necessary to click on the timeline to shift the video playback cursor in order for the edit field to open for entering text.

**Comment by schyatt** [comment]
This issue is present on both the main and beta sites.

**Comment by schyatt** [comment]
This is still an issue on the beta site.
![23](https://cloud.githubusercontent.com/assets/10120523/9827306/46c35004-589e-11e5-830f-6ff00731c9c9.gif)

**Comment by gliese1337** [comment]
Re-fixed.
