### ISSUE TITLE
Failure to Load Resources during Playback

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#650]
Simply accessing a video (https://ayamel.byu.edu/content/2107) generates these errors on the console:

![image](https://cloud.githubusercontent.com/assets/7268293/9661666/f0cfdbd0-5218-11e5-8758-fe186edda166.png)

**Comment by schyatt** [comment]
Issue present on both the beta and main sites.

**Comment by gliese1337** [comment]
Those are errors in Chrome extensions. They have nothing to do with our code.
