### ISSUE TITLE
Video Playback on Sartre Served Using  HTTP

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#652]
Video that is located on HVMIRROR on Sartre is being served using HTTP. The good news is that it still works.

![image](https://cloud.githubusercontent.com/assets/7268293/9662565/3dc18f02-521d-11e5-8229-f7673e7cba58.png)

**Comment by gliese1337** [comment]
That's because the URLs stored for those videos in the Resource Library are HTTP urls. If they need to be loaded over HTTPS, then someone needs to change the urls to be HTTPS urls.
