### ISSUE TITLE
Brightcove Video in Learning Suite via LTI

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#655]
I placed two exercises on Learning Suite, one from YouTube and one from Brightcove. The first plays fine, the second does not. 

https://learningsuite.byu.edu/.6VdT/cid-_tdimbOopGyQ/home

**Comment by gliese1337** [comment]
@DigitalProf : I went to the Learning Suite course, switched to Student View, went to Assignments, clicked on the Brightcove video assignment... and it worked. Brought up the Ayamel page and played just fine. What exactly is the nature of the error you encountered?

**Comment by DigitalProf** [comment]
This is what I get. I will clear cache and test again...
![image](https://cloud.githubusercontent.com/assets/7268293/9779445/e65cc5b2-5738-11e5-9891-1d086ea95bca.png)

**Comment by DigitalProf** [comment]
@gliese1337 : I am still getting the problem with a Brightcove video that works in one course but not in another. The two assignments are [present on Learning Suite here.](https://learningsuite.byu.edu/.UZ8S/cid-_tdimbOopGyQ/home/assignments)

This one works:

Url: https://ayamel.byu.edu/course/311/content/446/lti
Key: 311

This one fails:
Url: https://ayamel.byu.edu/course/65/content/446/lti
Key: 65

**Comment by schyatt** [comment]
Hi Dr. Bush,
So I tested it out on the beta site by creating a new course and
adding/creating new content from brightcove, and it did not work. I got the
same "oh snap" error message.
Here is the content url:  http://sartre3.byu.edu:9006/content/558
Url for the course:  http://sartre3.byu.edu:9006/course/93

I put it on the same Learning Suite course as mentioned above. The
assignment is callled, "Les enfants du marais"

On Thu, Sep 10, 2015 at 11:33 AM, DigitalProf <notifications@github.com>
wrote:

> @gliese1337 <https://github.com/gliese1337> : I am still getting the
> problem with a Brightcove video that works in one course but not in
> another. The two assignments are present on Learning Suite here.
> <https://learningsuite.byu.edu/.UZ8S/cid-_tdimbOopGyQ/home/assignments>
>
> This one works:
>
> Url: https://ayamel.byu.edu/course/311/content/446/lti
> Key: 311
>
> This one fails:
> Url: https://ayamel.byu.edu/course/65/content/446/lti
> Key: 65
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/655#issuecomment-139319864>
> .
>



-- 
Shari Hyatt

**Comment by DigitalProf** [comment]
@gliese1337 : I just successfully accessed from Canvas a movie on Brightcove. It is from the same course that worked on Learning Suite:
https://ayamel.byu.edu/course/311/content/620/lti

**Comment by schyatt** [comment]
When I try to click on the link for the video that fails, I get the
attached error:



On Thu, Sep 10, 2015 at 11:33 AM, DigitalProf <notifications@github.com>
wrote:

> @gliese1337 <https://github.com/gliese1337> : I am still getting the
> problem with a Brightcove video that works in one course but not in
> another. The two assignments are present on Learning Suite here.
> <https://learningsuite.byu.edu/.UZ8S/cid-_tdimbOopGyQ/home/assignments>
>
> This one works:
>
> Url: https://ayamel.byu.edu/course/311/content/446/lti
> Key: 311
>
> This one fails:
> Url: https://ayamel.byu.edu/course/65/content/446/lti
> Key: 65
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/655#issuecomment-139319864>
> .
>



-- 
Shari Hyatt

**Comment by schyatt** [comment]
When I try to access the video that Dr. Bush said failed for him, it worked just fine for me and Logan.

**Comment by DigitalProf** [comment]
@gliese1337 @schyatt : Please note that I just tried this on a newly updated copy of Firefox from the same computer, and I get the same response. I cleared the cache and got the same problem

**Comment by schyatt** [comment]
It is working for me on both Firefox and Chrome.

On Fri, Sep 11, 2015 at 12:38 PM, DigitalProf <notifications@github.com>
wrote:

> @gliese1337 <https://github.com/gliese1337> @schyatt
> <https://github.com/schyatt> : Please note that I just tried this on a
> newly updated copy of Firefox from the same computer, and I get the same
> response. I cleared the cache and got the same problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/655#issuecomment-139622921>
> .
>



-- 
Shari Hyatt

**Comment by gliese1337** [comment]
Closing for non-replicability.
