### ISSUE TITLE
xAPI: 'webkitMovementX' Deprecated

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#656]
Accessing this video on the Beta Site, I received these errors:
![image](https://cloud.githubusercontent.com/assets/7268293/9797878/c663f6ae-57ba-11e5-92bc-60e9207239d6.png)

**Comment by gliese1337** [comment]
That's not our code. The warning comes from the YouTube player. Also not a consequential error- just a deprecation warning so that their developers know that they ought to be using a more up-to-date API.
