### ISSUE TITLE
When saving annotations, user gets un-needed/ incorrect warning. 

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#658]
When I save annotations, I am told that my changes have been saved, but then when I go to exit the annotation editor, I get a warning that some changes may not have been saved, and I could lose them if I leave the page. This warning is incorrect, however, because my changes are saved.
This happens on the Main and Beta sites.
![saving](https://cloud.githubusercontent.com/assets/10120523/9824898/39ee3f76-588d-11e5-9c9c-e122f1633887.gif)

**Comment by verdude** [comment]
5b19aede3a2e68213f01910ee842a02622bb39c3
