### ISSUE TITLE
Cannot right click in timeline and access the menu

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#659]
When I right click in the transcript bar in captionAider, I am unable to see a menu that gives me the options to edit the track (such as auto fill and all that jazz). Instead I am given a menu as seen in the .gif. This happens on both the main and beta sites. 
url for video:  https://ayamel.byu.edu/content/2737
![1](https://cloud.githubusercontent.com/assets/10120523/9826927/00624fa0-589b-11e5-8035-4aa08f58a251.gif)

The menu that should show up (as seen on chrome)
![menu](https://cloud.githubusercontent.com/assets/10120523/9826987/7198fb38-589b-11e5-9ea9-181fc0ef452a.PNG)

**Comment by gliese1337** [comment]
I managed to replicate this once, but upon refreshing the page, the error went away. I suspect it's a version-shear problem. You probably just need to clear your cache to ensure that you have the most up-to-date code for all components.

**Comment by schyatt** [comment]
I cleared my cache and am still running into the same issue. Also, we just had another user (Gavin Asay) run into the same issue.

**Comment by schyatt** [comment]
I am also experiencing the issue on Chrome, now.

**Comment by gliese1337** [comment]
Replication information as reported by Gavin Asay:

    The second bug is more minor and has a workaround, but is probably worth your attention.
    After creating a new track (not showing a previously existing track), the right-click menu no
    longer works properly. Instead of displaying Ayamel’s right click menu when right clicking, it
    displays a browser menu.
    If you save the empty subtitle track and reload the page, then you can simply show the track
    and then right click works as intended.
