### ISSUE TITLE
Mac-Safari- Captionaider- Saving to Disk opens the file in a new tab

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#669]
When a user saves to Disk in Captionaider on Safari the file does not download, instead it opens in a new tab.
![safarisavingerror](https://cloud.githubusercontent.com/assets/5481718/10259237/40534946-6923-11e5-868f-5bc4c54a84a7.gif)

The file should download and create the specified content and ask the user where to place the file.

Tagged as low priority because users can still copy/paste that text file and create a caption file using a texteditor, but it is inconvenient.

**Comment by gliese1337** [comment]
This is a Safari issue- as in, Safari does not support the necessary API for saving files, and there is nothing we can do about that. I consider this a reasonable fallback.
