### ISSUE TITLE
Cannot Export words to Quizlet

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#670]
This is happening on both the main site and ayamelbeta in all three browsers.
![3792ad12b8c17931d58161bac959cb31](https://cloud.githubusercontent.com/assets/5481718/10259554/d6643d34-6926-11e5-9a87-96618152e502.gif)

When a user clicks on "Export Selected to Quizlet" they get a "Cannot continue" error with the following message:

A problem has occurred when trying to allow a third-party application access to your account.
If you feel this is a mistake, please [send the Quizlet staff some feedback](https://quizlet.com/feedback).

**Comment by verdude** [comment]
Works on the beta site. It was a key issue. I'm not sure what was wrong with the keys but I made a new account and it works.
We need to figure out what quizlet account we want to use with ayamel beta and the production site (I think we need one account per site).
