### ISSUE TITLE
Annotations do not show up when you click on them in the captions

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#675]
The annotation did not show up when I clicked on it in the caption. Instead, it came up with a dictionary definition/ translation.
url:  https://ayamel.byu.edu/content/131
![annotation](https://cloud.githubusercontent.com/assets/10120523/10284436/406efdf6-6b41-11e5-986b-2c450fe8e8c6.PNG)

**Comment by verdude** [comment]
You need to enable the actual track in the configuration for the video.
