### ISSUE TITLE
Error Saving Track

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#677]
Using CaptionAider with Chemistry Video, 2772:
https://ayamel.byu.edu/captionaider/2772/0

It saved to disk, but it did not appear to save to the server.

We are getting "Mixed Content" errors and "Uncaught ReferenceError: ADL is not defined"
![image](https://cloud.githubusercontent.com/assets/7268293/10471310/e90bbf08-71d1-11e5-80c4-b41e52ec25a6.png)

When I tried to leave the page, I received this popup box:

![image](https://cloud.githubusercontent.com/assets/7268293/10487341/b559de04-7250-11e5-89e2-6090ce0aeca6.png)

I saved the track to disk, then reloaded it. After adding some more captions, I tried once again to save and received this message:

![image](https://cloud.githubusercontent.com/assets/7268293/10488131/7095a718-7254-11e5-945d-0570da1bc5e2.png)

I received the same message that I had not saved the current version of the caption track. I was able to save to disk and load the captions.

**Comment by gliese1337** [comment]
This is due to the video player trying to make xAPI calls despite the necessary libraries not having been loaded on the CaptionAider web page.
This should have been resolved along with #651 .
I'll leave this issue open until we can test it on the main site after the next release cycle, just in case.

**Comment by DigitalProf** [comment]
Given the situation, I just changed this to Priority 1.

Luckily, I understand from a previous message today that Santi has completed the extrication of the xAPI calls from CaptionAider, which I guess was #651 to which Logan referred.

This issue underscores the importance of testing the Beta Site, so I am Ccing Shari and Jeff so we can see where things stand. Once we determine we are good to go, then we can push the code to the Production Site.
