### ISSUE TITLE
Annotation Editor Fails to Register Change

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#679]
When making changes to annotations, they are saved as shown below, but the editor fails to register that the "save" took place:

![image](https://cloud.githubusercontent.com/assets/7268293/10493680/abb31a5e-726f-11e5-9cce-d857675e718b.png)

After seeing that screen and clicking on the arrow to return to the content, the system pops up this message:

![image](https://cloud.githubusercontent.com/assets/7268293/10493735/f250bade-726f-11e5-9c1a-f75413d4297e.png)

**Comment by gliese1337** [comment]
See #658
