### ISSUE TITLE
Back Arrow on Chrome Does Not Work (Ayamel Beta)

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#685]
Starting with this course:
https://ayamelbeta.byu.edu/course/34

I select any video, which comes up just fine at this URL:
https://ayamelbeta.byu.edu/content/354

When I click on the back arrow, the browser switches to this URL:

https://ayamelbeta.byu.edu/course/34/content/354

There is no return destination available with the button.

**Comment by gliese1337** [comment]
Videos open in new tabs; the back button is not supposed to work, and never has- the course page remains open in the original tab instead.
