### ISSUE TITLE
Audio stops when playback speed is less than .75

### ISSUE THREAD

**Issue by verdude** [BYU-ARCLITE/Ayamel-Examples#693]
When you lower the playback speed by more than one notch, then the audio turns off.

I'm not sure if this works as designed or if we just haven't gotten to it yet.

**Comment by gliese1337** [comment]
This will vary with the different underlying player plugins- some will keep the audio going at lower speeds than others. Normalizing that behavior would require having access to a separate audio stream and writing our own audio processing code, which is complicated but definitely doable... except that we also can't always get access to the raw audio data stream, either. So, there's not much point.

**Comment by gliese1337** [comment]
This is variable behavior between the different underlying player plugins.
To normalize it, we'd have to write our own audio processing code to work on the raw audio stream separate from the individual video plugins, which is complicated but doable... except that we *also* can't always (in fact, usually can't) get access to the raw audio stream anyway, also dependent on the underlying player. So, there's not much point building all that extra infrastructure.
