### ISSUE TITLE
Adjust Video Size to Browser Window Size

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#698]
Ayamel opens just fine, but the entire screen is not visible on the learner's screen. This comes from the fact that the browser has been adjusted according to the resolution of the computer screen.

**Comment by gliese1337** [comment]
Duplicate of #624

**Comment by DigitalProf** [comment]
The workaround to this issue is to re-size the window by using the lower right hand corner and then moving the mouse left-to-right/right-to-left predominantly, rather than top-to-bottom/bottom-to-top.
