### ISSUE TITLE
Beta: Annotation Editor does not pull up the transcript

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#702]
When I go into the Annotation Editor for a video that has a caption track uploaded, no transcript shows up, so I am unable to make any edits. I checked this on multiple videos.
Video url:  https://ayamelbeta.byu.edu/annotations/84/
![annotations](https://cloud.githubusercontent.com/assets/10120523/11158232/0e83215e-8a14-11e5-94f0-5f67784bc1d1.PNG)

**Comment by JKJensen** [comment]
Same Problem on Mac as well
