### ISSUE TITLE
Beta:  Cannot Disable Annotation Tracks

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#703]
When I disable a caption track, they still show up as an option for the viewer to use. I tried refreshing and clearing my browser.
video url:  https://ayamelbeta.byu.edu/content/84
![disable2](https://cloud.githubusercontent.com/assets/10120523/11158473/a04c19a0-8a15-11e5-9254-dfbdd531f713.PNG)
![disable1](https://cloud.githubusercontent.com/assets/10120523/11158474/a3e72802-8a15-11e5-8deb-de4d959cee7d.PNG)

**Comment by gliese1337** [comment]
Is this problem also present on the main site? We need to know if it's a regression or not in order to make decisions about releases.

**Comment by schyatt** [comment]
No, it works fine on the main site.

**Comment by gliese1337** [comment]
Closing as duplicate of #671
