### ISSUE TITLE
Beta Site: Mac: Cannot login via Google

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#704]
All three major browsers on Mac cannot login via Google account on AyamelBeta.byu.edu.
The following error appears:
<img width="681" alt="2015-11-16 18 00 14" src="https://cloud.githubusercontent.com/assets/5481718/11199606/3e5a63cc-8c8c-11e5-8434-5c89178c46fa.png">

The main site still works fine.

**Comment by gliese1337** [comment]
This is probably because nobody updated the google account configuration when we changed the domain name for the beta site.
