### ISSUE TITLE
Batch upload is not uploading anything

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#705]
Every time I try to add something via batch upload, it will give me a notification immediately saying the upload is complete.

However, when I go to look for my videos they do not show up. No new videos are created.

This is the tab delimited file I was trying to use:
[BulkUploadTest.txt](https://github.com/BYU-ARCLITE/Ayamel-Examples/files/36184/BulkUploadTest.txt)

**Comment by dro248** [comment]
I'm not sure what tool you used to create your tab-delimited text file. I created mine using Excel, filled in  each of cells with good values and then exported it as a tab-delimited file and it worked.

See #708 

Here is the working file:
[batch1.txt](https://github.com/BYU-ARCLITE/Ayamel-Examples/files/39543/batch1.txt)
