### ISSUE TITLE
Ayamel Player transcript sometimes shows up blank until text is hovered over.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#709]
This bug is kind of difficult to replicate. But every so often [on this piece of content](https://ayamel.byu.edu/content/2458) the text will not display in the transcript. However, if the user hovers over the text, it will display.

![0475c438ea3b5ba5a2ce6121c6d47b6c](https://cloud.githubusercontent.com/assets/5481718/11359403/0c52e7ac-9239-11e5-951f-19a4af0a2884.gif)

This problem seems to happen most often on the English02 track in that content.

**Comment by DigitalProf** [comment]
Thanks to Jeff for carefully documenting the issue. I raised its priority due to the fact that its occurrence suggests that the software is not working.

**Comment by gliese1337** [comment]
Well, I've managed to replicate this, but there is no indication of anything going wrong in our code- no errors are thrown, nothing in the inspector changes when you hover; as far as the dev tools are concerned, the text has already been properly rendered. Best I can figure, it's a browser bug of some sort.
Given that there is no obvious way to work around it, and the transcript viewer needs ground-up replacing anyway, it's probably not worth working on this.
