### ISSUE TITLE
Revamped Batch upload system

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#710]
When a user uploads a .txt Tab Delimited file, the page should populate a table of the interpreted data.

Then when the user hits the "start batch" button, the uploaded videos should highlight in green when the video is correctly uploaded.
<img width="1208" alt="ayamelbatchuploadformat" src="https://cloud.githubusercontent.com/assets/5481718/11483408/69c9c5a0-9765-11e5-9496-916e39795ef4.png">

If a video fails, it should highlight the row in light red.

Checkboxes on the side also indicate the status of the videos as they are being uploaded.

You can use [fa-square-o](http://fortawesome.github.io/Font-Awesome/icon/square-o/) for a blank check, [fa-exclamation-triangle](http://fortawesome.github.io/Font-Awesome/icon/exclamation-triangle/) for broken files, and [fa-check-square-o](http://fortawesome.github.io/Font-Awesome/icon/check-square-o/) for a successfully uploaded file.

If some of the videos failed to upload, a download link should appear for the user to download a tab-delimited text file of the unsuccessful rows.

**Comment by gliese1337** [comment]
Track under #168
