### ISSUE TITLE
Add a confirmation pop-up before a teacher deletes a student from a course

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#712]
When a teacher deletes a student from the Course Members directory, the student is immediately removed from the course.
<img width="567" alt="2015-12-01 16 05 41" src="https://cloud.githubusercontent.com/assets/5481718/11517228/a0027b40-9845-11e5-9d45-8aa93490c6cb.png">

After they click the "Remove" button, a confirmation window should come up. This window would ask them to confirm that they would like to remove [STUDENT NAME] from the course.

**Comment by dro248** [comment]
Hey Jeff, I added this additional functionality a week or so ago. However, what with the beta site being down, I haven't been able to show you. I wanted to make sure that it looked good to you prior to closing this issue.
