### ISSUE TITLE
Lookup for Arabic on Y-Lex

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#714]
Insert a temporary conditional into Y-Lex such that if it receives the ISO 639-2 codes of “apc” or “arc” that the lookup be done using the ISO 639-2 code of “arb”. 

If some dictionary sources only work with ISO 639-1 codes, then we should use “ar” as was done previously.

**Comment by gliese1337** [comment]
Although language-code fallbacks as requested were implemented, translation is still failing on https://ayamel.byu.edu/content/1013 (and probably other Arabic videos as well).
Neither individual words nor whole sentences return any translations, as demonstrated in these screenshots:
![cf21f1f9-df18-452d-9a55-88057fe1a468](https://cloud.githubusercontent.com/assets/828051/12659093/252b192e-c5ca-11e5-9bdf-b886dac8f3cb.png)

![image002](https://cloud.githubusercontent.com/assets/828051/12659076/0da654a8-c5ca-11e5-9b23-7ea66bdd230f.jpg)
