### ISSUE TITLE
Can't save to server while in Captionaider

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#715]
When I hit the save button in CaptionAider to save subtitles, nothing occurs. No dialogue box comes up saying I saved successfully or that it failed. (But I can change the save location to the disk and workaround to saving the subtitles outside of CaptionAider.)

I've tested this problem on a Mac in Firefox/Chrome under Admin and normal accounts. This is also a problem on the Beta Site.

**Comment by DigitalProf** [comment]
Upon testing, the system responds with the "captions saved" message, but the save does not happen, at least with "save to server." Saving to disk DOES work. These messages were present on the console:

![image](https://cloud.githubusercontent.com/assets/7268293/12274636/fd8693ba-b928-11e5-805c-811d7a845cdc.png)
