### ISSUE TITLE
On menu before Captionaider- Notify user if they are saving a Caption with the same name as a previous caption

### ISSUE THREAD

**Issue by natatat9** [BYU-ARCLITE/Ayamel-Examples#717]
On this particular video, we were having problems seeing 3 out of the 4 tracks that are added onto the video.  The subtitles show up on the video itself, but there are no other tracks below.

Here's the link to the video that we are working on:

https://ayamel.byu.edu/captionaider/3137/0

Thanks!

**Comment by JKJensen** [comment]
This is also a problem on Chrome on Mac.

![notshowingmultipletracksincaptionaider](https://cloud.githubusercontent.com/assets/5481718/12099802/0aa0e2ea-b2e8-11e5-8f7a-66511a70fcb8.gif)

**Comment by DigitalProf** [comment]
Natalie and Jeff, what are the chances this is related to the fact that every track has exactly the same track name?

**Comment by JKJensen** [comment]
It looks like that's the problem. Captionaider will only display differently named subtitle tracks.
It will display one subtitle track each of tracks named the same.
![e12d567bfbaee0f1598465af72884b59](https://cloud.githubusercontent.com/assets/5481718/12103742/4b855196-b302-11e5-93a3-0d388135e19e.gif)
