### ISSUE TITLE
Annotations Displayed when Non Enabled

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#723]
These were being displayed so I enabled them, then disabled them. They still show up:

![image](https://cloud.githubusercontent.com/assets/7268293/12279396/112a399c-b944-11e5-888d-3101c947e0c3.png)

![image](https://cloud.githubusercontent.com/assets/7268293/12279418/31dca3fa-b944-11e5-92a3-f9416f59455a.png)

**Comment by gliese1337** [comment]
URL?

**Comment by gliese1337** [comment]
Duplicate of #671
