### ISSUE TITLE
Transcript and Definition bar on player disappear in fullscreen

### ISSUE THREAD

**Issue by natatat9** [BYU-ARCLITE/Ayamel-Examples#724]
The transcript and definition bar disappeared while watching a video in full screen.  I can open the bar once, but after I close it, it doesn't reappear until I exit full screen and reopen it.  (This doesn't work in Chrome, but it does in firefox on my PC, I'm not sure about MACs)

**Comment by gliese1337** [comment]
Link to replicate?

**Comment by natatat9** [comment]
sorry about that! I actually think the bug might have been resolved.  I haven't been able to replicate the bug since the annotations tab has been added to the video player's side bar.  Here is the video I test before and after the annotation bar had been added.  https://ayamel.byu.edu/content/2010

**Comment by gliese1337** [comment]
Thanks. The bug was slightly non-deterministic, but it should be fixed now.
