### ISSUE TITLE
Cannot Create New Caption Track

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#725]
Trying to add a new caption track to this video:
https://ayamel.byu.edu/captionaider/3271/0

I received this action:
https://arclite.byu.edu/hvmirror/AyamelTutorial/AyamelNewTrackError.mp4

In other words clicking on the language took me away from the "Create New Track"  dialog box, with no new caption track being created.

**Comment by gliese1337** [comment]
OK, this should be fixed on the main site now, but still a problem on the Beta site.
It seems to be related to upgrading Ractive, so I just rolled back some code on the main site to an earlier version.

**Comment by DigitalProf** [comment]
This makes sense... I seem to remember that one of the console errors that I mentioned I was not able to save mentioned Ractive.

**Comment by DigitalProf** [comment]
The issue with not being able to create the track is resolved, but now it is not possible to save the caption track to the server but saving to disk works fine. I opened a new issue as follows:

Cannot Save Caption Track to Server #726<https://github.com/BYU-ARCLITE/Ayamel-Examples/issues/726>
