### ISSUE TITLE
Cannot Save New Caption Track to Server

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#726]
I created a caption track using Auto Cue/Auto Fill. I am unable to save the track to the server, although I was able to save to disk and then upload the file. I also tried cloning the track to see if I could save that one. Neither would save.
![image](https://cloud.githubusercontent.com/assets/7268293/12768575/b5e01044-c9cd-11e5-8a65-05dae46f90a2.png)

**Comment by gliese1337** [comment]
How do you know it didn't save? Does it claim to save, and then the track doesn't show up on the content page? Do the track backgrounds never turn blue?

**Comment by DigitalProf** [comment]
It never claims to save, and the track is never there afterwards.

I sent the graphic, but the only color I remember is a green border around the caption track.

**Comment by DigitalProf** [comment]
It also warned me about leaving the CaptionAider page just as it always does when the caption track is not saved.

Sent from my iPhone

On Feb 2, 2016, at 10:53 PM, Michael Bush <michael_bush@byu.edu<mailto:michael_bush@byu.edu>> wrote:

It never claims to save, and the track is never there afterwards.

I sent the graphic, but the only color I remember is a green border around the caption track.

**Comment by gliese1337** [comment]
Well, that was weird. The problem was only with saving *new* tracks, not saving changes to existing tracks. And as far as I can tell, it shouldn't have been working for quite some time. The bug was subtle, and introduced quite a while ago. Have we just not had anybody creating new tracks since... November, at least?

**Comment by DigitalProf** [comment]
The weirdest part is that yesterday in the demo I was able to create a new caption track at first. The problem did not appear until later in the demo session

It is great that the bug was caught.
