### ISSUE TITLE
Add "Clone with Translation" option to Captionaider

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#728]
<img width="334" alt="screenshot 2016-02-03 11 19 45" src="https://cloud.githubusercontent.com/assets/5481718/12792876/0feba31c-ca6b-11e5-9203-5ffe4359f9e3.png">

In Captionaider, in addition to the two normal clone options, add a third option called "Clone with Translation."

When a user clicks on "Clone with Translation," a box to name the track and then a language selection box will pop up.
Upon selecting the language, the time codes will be cloned. And the language of the subtitle track will change to the one the user selected.
Each cue will be sent through the Google Translate API and the machine translated cue will fill each of the cues on the new translated track.

**Comment by gliese1337** [comment]
I've set it up to go through Y-Lex, rather than directly to Google Translate, because that is much simpler and avoids duplicating the Google Translate interface code.
