### ISSUE TITLE
Problem with adding new lines in Batch Upload Utility in Firefox

### ISSUE THREAD

**Issue by dro248** [BYU-ARCLITE/Ayamel-Examples#729]
![firefox_bug](https://cloud.githubusercontent.com/assets/11342204/12854652/16badfee-cbf8-11e5-8e21-2b42bc9bedfa.png)

When clicking the add line button in Firefox, the line is incorrectly created above the table header.

**Comment by dro248** [comment]
![firefox_bug](https://cloud.githubusercontent.com/assets/11342204/12854652/16badfee-cbf8-11e5-8e21-2b42bc9bedfa.png)

When clicking the add line button in Firefox, the line is incorrectly created above the table header.

**Comment by gliese1337** [comment]
I recommend making better use of Ractive to handle the DOM manipulations for you. The current `addRow` function duplicates functionality that's already built-in. You can similarly simplify submitRow, clearTable, and so forth.
