### ISSUE TITLE
"Clone with Translation" Adding Quotes

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#731]
With this content object: https://ayamelbeta.byu.edu/content/579

The "Clone with Translation" option adds quotes to the translated captions:
![image](https://cloud.githubusercontent.com/assets/7268293/12868002/83bd7310-ccb9-11e5-82cf-045844440d00.png)

**Comment by gliese1337** [comment]
I think this is most appropriately handled in the Google Translate module in Y-Lex.
