### ISSUE TITLE
"Clone with Translation" Not Handling Single Quotes

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#733]
With this content object: https://ayamelbeta.byu.edu/content/579

As shown in this screen snippet, "Clone with Translation" is not properly handling single quotes received back from Google Translate.

![image](https://cloud.githubusercontent.com/assets/7268293/12868046/2d98d248-ccbb-11e5-9a4d-5de089d6e5c4.png)

**Comment by gliese1337** [comment]
Hm. This looks reasonably straightforward. I'll get on it tomorrow.
