### ISSUE TITLE
Syrian and Egyptian Arabic Language Codes not on Ayamel

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#738]
On CaptionAider and on the Ayamel Player, the options do not exist to select Syrian (arz) and Egyptian (apc). This does functionality **DOES **exist on the Y-Lex test page.

I added captions to [this Syrian video](https://ayamelbeta.byu.edu/content/496) for testing. The captions are "apc", but these were of course uploaded as "ara". Ayamel on the Beta Site works great for a word (حديثك) and provides these results

![image](https://cloud.githubusercontent.com/assets/7268293/12898018/b102629a-ce67-11e5-959c-b0abdeeb82cd.png)

[Here is a table](http://www-01.sil.org/iso639-3/codes.asp) of two and three-letter language codes that might be useful.

Testing a word (حديثك) from the test video above using the Y-Lex Test Page, I get these results:

![image](https://cloud.githubusercontent.com/assets/7268293/12897845/1e171962-ce67-11e5-907a-be7b0502f6ee.png)

**Comment by daganrh** [comment]
dro248 and I believe that we fixed this one, It was pushed to beat site
