### ISSUE TITLE
How do I download Activity Stream statistics?

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#743]
I thought the "download excel activity stream" used to be under the "Edit" menu on a content page. But I can't find that option anywhere.

<img width="666" alt="screenshot 2016-02-09 13 48 38" src="https://cloud.githubusercontent.com/assets/5481718/12930146/dc46da04-cf33-11e5-8a89-c636299f39b6.png">

How do I download an excel spreadsheet of the activity stream information?

**Comment by DigitalProf** [comment]
We have removed Activity Stream data collection. Learner activity data is now saved using xAPI to an open source learning record store (LRS) called Learning Locker.
