### ISSUE TITLE
Resizing the window causes the video Sidebars to dissappear

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#745]
When I resize my web browser on Mac Chrome, the Sidebars will sometimes disappear in the Ayamel Player.
![resizingplayersidebarproblem](https://cloud.githubusercontent.com/assets/5481718/13194336/9f7ed0ac-d74b-11e5-8910-464d59902b4f.gif)

[Sample video](https://ayamelbeta.byu.edu/content/670).

**Comment by gliese1337** [comment]
@JKJensen There's a fair chance that this is fixed now, but I don't have a Mac to test it on. Can you check and then either close this issue or comment so I know it's still broken?

**Comment by JKJensen** [comment]
Yep! You fixed it!
