### ISSUE TITLE
Arabic Dialects Not Available on Captions/Subtitles Upload Page

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#751]
I would have sworn that I remembered it being discussed that North Levantine and Egyptian had been added. I just checked, but I did not find these on the Beta Site or on the Production Site.

![image](https://cloud.githubusercontent.com/assets/7268293/13361660/48696318-dc7d-11e5-9aed-7acbdbaf37df.png)

**Comment by gliese1337** [comment]
They were added to the content-upload page, and the settings page, but not to the Additional Documents dialog or to CaptionAider. That has been remedied.
