### ISSUE TITLE
Formatting of Definitions Window

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#752]
It seems like we need to add a few pixels of white space between the "Select Language" button and the area where definitions are displayed:
![image](https://cloud.githubusercontent.com/assets/7268293/13407147/22dc7428-dee4-11e5-8957-7586015550ff.png)

**Comment by gliese1337** [comment]
I did one better and added a separating line.

**Comment by DigitalProf** [comment]
[As demonstrated with this Finnish music video](https://ayamel.byu.edu/content/1766), the situation is improved, but the down arrow is missing on the vertical scroll bar in the definitions window:
![image](https://cloud.githubusercontent.com/assets/7268293/13440163/f4e07ef0-dfad-11e5-86b2-3ed4d313af08.png)
The same problem exists in the transcript window, which it would appear also hides the bottom (end) of the transcript as shown below. Note that when you click on the last entry in the transcript, the video is not at the end and keeps playing but the final captions are not displayed in the window.
![image](https://cloud.githubusercontent.com/assets/7268293/13440350/e11f4e36-dfae-11e5-846b-d71c1c45ece0.png)

**Comment by DigitalProf** [comment]
With [this movie](https://ayamel.byu.edu/content/2926), After looking up several words one after the other, the window eventually filled, but the down error never appeared. The most definition was always displayed in the window, however.

![image](https://cloud.githubusercontent.com/assets/7268293/13441515/c95e3b26-dfb4-11e5-81c6-5a71e5167fdd.png)

**Comment by gliese1337** [comment]
That movie is on the main site. It's been fixed on development. Id this high enough priority to be hotfixed?

**Comment by DigitalProf** [comment]
I guess not...

It might make sense to have it by Friday so things look sharp for Saturday.

Sent from my iPhone

On Mar 1, 2016, at 1:57 PM, Logan Kearsley <notifications@github.com<mailto:notifications@github.com>> wrote:


That movie is on the main site. It's been fixed on development. Id this high enough priority to be hotfixed?

-

**Comment by gliese1337** [comment]
Dangit! This was fixed! And now it is unfixed, and I don't know why... Guess I'll be working on this tonight.

**Comment by gliese1337** [comment]
OK, this should be re-fixed now....
