### ISSUE TITLE
Mac-Firefox only: Ayamel player will not display

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#753]
On Mac Chrome and Safari the Ayamel player will display for [this Youtube](https://ayamel.byu.edu/content/2450) and [this Brightcove](https://ayamel.byu.edu/content/2877) video.

However, Mac Firefox will not display any part of the Ayamel player:
<img width="1199" alt="screenshot 2016-03-02 11 36 47" src="https://cloud.githubusercontent.com/assets/5481718/13470890/66fba61e-e06b-11e5-9001-dd45ea55c4db.png">

Oddly, [this is not a problem on the beta site](https://ayamelbeta.byu.edu/content/574).

**Comment by gliese1337** [comment]
@daganrh I'm assigning this to you because you have a Mac laptop, so you can actually test this.

**Comment by JKJensen** [comment]
This is currently not an issue on my MacBook Pro (Mid 2015) 
Running OS X: 10.11.4
Graphics: Intel Iris Pro 1536 MB.

**Comment by dro248** [comment]
Could not duplicate.
