### ISSUE TITLE
UX for saving captions to show that the caption is currently saving

### ISSUE THREAD

**Issue by dro248** [BYU-ARCLITE/Ayamel-Examples#757]
![ui_issue](https://cloud.githubusercontent.com/assets/11342204/13896742/2ef0e4d8-ed5d-11e5-98b0-1b9080f355e4.png)

When saving a subtitle track in CaptionAider, the user experience is unreliable in that when the user clicks the save button, there is no follow-up event triggered (e.g. a spinner that says "saving").

Rather than an alert that may or may not show up, on successful save, a green box saying "{{caption.name}} saved successfully."

If the server fails, it should alert the client to reattempt to save. If that is too troublesome, perhaps a timeout should be added such that on any given save, if it takes too long, the user will be alerted and can reattempt to save.

**Comment by JKJensen** [comment]
A "thing" (Dialogue Box or something else) should float in the middle of the screen that says: "Saving [With a spinning animation]"
Users should still be able to work on their captions while the dialogue box is on top saving.
An error should be returned if the saving is unsuccessful.

**Comment by dro248** [comment]
I've changed the user experience for saving in CaptionAider. @JKJensen , if you wouldn't mind testing it to make sure that it is up to snuff.

I still have to fix where it is grabbing the icons from.
