### ISSUE TITLE
CaptionAider: Creating a new subtitle track and saving/editing it multiple times creates multiple tracks

### ISSUE THREAD

**Issue by schyatt** [BYU-ARCLITE/Ayamel-Examples#761]
When I create captions in CaptionAider, it creates 2 caption tracks in both configuration and under the caption/subtitles menu. The tracks are identical unless you make any edits in CaptionAider. After that, the duplicate remains how it was before you made any edits.
![capture](https://cloud.githubusercontent.com/assets/10120523/14502669/aa446c34-0169-11e6-9d5a-5b7963ff4d1d.PNG)

**Comment by JKJensen** [comment]
Here is a video explanation of this problem:
https://ayamelbeta.byu.edu/content/718

Essentially, it's impossible to edit subtitles. You can only create a new set while leaving the old one behind.
