### ISSUE TITLE
Bulk Uploader- Off by one error prevents first file in a batch from being loaded in

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#762]
When I try to upload the following .csv tab delimited file, only the latter 4 entries get inputted into the bulk uploader system, not the first entry.

[AlKitaabArabic-tinyUpload.txt](https://github.com/BYU-ARCLITE/Ayamel-Examples/files/219676/AlKitaabArabic-tinyUpload.txt)

**Comment by dro248** [comment]
This issue stems from always testing our csv files with headers in them. Now, you can have it either way.
