### ISSUE TITLE
Bulk Uploader- Labels category not uploading properly

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#763]
When I upload a video using the bulk upload tool, the labels will not fill in based on what I input.

Example file:
[AlKitaabArabic-tinyUpload.txt](https://github.com/BYU-ARCLITE/Ayamel-Examples/files/219801/AlKitaabArabic-tinyUpload.txt)

**Comment by dro248** [comment]
Fixed.
