### ISSUE TITLE
Captions Not Displayed on Video During Autocue/Autofill

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#770]
When:

1. No caption file is present
2. A new track is created
3. Text is added to the line buffer
4. AutoCue and AutoFill are activated
5. Captions are added

The end result is that the new track WILL NOT display on the video.

**Comment by JKJensen** [comment]
Gif Explanation:
![captionsnotshowingup](https://cloud.githubusercontent.com/assets/5481718/14870049/b1a4a40e-0c94-11e6-948a-6977bc0237ce.gif)

Creating a cue from the Buffered text does not display the subtitle edit area in the player window.

**Comment by gliese1337** [comment]
This seems to have fixed itself. I can no longer replicate in on the beta site.
