### ISSUE TITLE
Image content objects are not displaying

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#776]
When a user uploads their own image for a content object, the image will not display.

<img width="677" alt="screenshot 2016-05-03 17 55 24" src="https://cloud.githubusercontent.com/assets/5481718/15001973/7a464782-1159-11e6-8435-8e7c72c79693.png">
This is a problem on both the [beta site](https://ayamelbeta.byu.edu/content/692) and the [main site](https://ayamel.byu.edu/content/3913).

The thumbnail for an uploaded image will view correctly, but the thumbnail for a url based image will become the Ayamel login screen background.
<img width="878" alt="screenshot 2016-05-03 18 05 21" src="https://cloud.githubusercontent.com/assets/5481718/15002005/dc1ba844-1159-11e6-9bdb-bee0576b599d.png">

**Comment by gliese1337** [comment]
Image support still isn't great, but at the very least they are now displayed.
Turns out we already had the plugin written, it just got removed from the content page includes at some point.
