### ISSUE TITLE
Remove "Administrator" from the Permission Request Form

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#780]
Is there a reason "Administrator" is on the [Permission Request Form](https://ayamelbeta.byu.edu/user/permission/request)?

We will soon be having a lot of users accessing that page. And I don't see why it should be an option available to anyone outside of the lab. If we need to make someone an Admin, we can do so on a case by case basis in the Admin Dashboard.

Is it alright if we removed "Administrator" so that there's no confusion?

**Comment by gliese1337** [comment]
There is a reason. It's because all of the permissions are defined in one place, and the request form is auto-generated. It would take extra special-case code just to exclude "admin".

But, if we only need that in the Request form, it's probably OK.
