### ISSUE TITLE
When captions end with a new line instead of a space, Y-Lex looks up the end word and the starting word as a combined word.

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#789]
Right now when a user goes to look up several lines of text, the words they are looking up may be concatenated based on the position of the word in the caption.

Specifically:

`This time, it was the plants that had changed`
`both the climate and the geology of Earth.`
The "changed both" is sent as one word with this response from Y-Lex:
`"今回は、それは気候と地球の地質をchangedboth持っていた植物でした。"`

![image](https://cloud.githubusercontent.com/assets/5481718/15554236/6a8c685c-2280-11e6-9862-9afa85ebac7a.png)

However, there are some instances where users put a space at the end of the line, which translated the sentences properly.
![extraspace](https://cloud.githubusercontent.com/assets/5481718/15554336/e410277c-2280-11e6-9435-4061fb2f236e.gif)

Y-Lex should work in both of these scenarios, adding in a space at the end of a newline where needed.

[Sample video to work with.](https://ayamelbeta.byu.edu/content/696)

**Comment by gliese1337** [comment]
Found the code we needed in CaptionAider and added a call to it in the regular translation pipeline. This should be fixed now.
