### ISSUE TITLE
Let users know when they are attempting to translate more than one word into the same Language

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#791]
Right now when a user highlights a whole phrase (and the language they're translating into is the same as the source), they get a generic error message.

![image](https://cloud.githubusercontent.com/assets/5481718/15556602/e8f511d4-228b-11e6-9907-06676d78d3a9.png)

The user should instead get a message like the following:
"You are currently translating a phrase from [LANGUAGE-X] to [LANGUAGE-X]. Please change the desired language. Or select a single word to view a definition."

Be sure to avoid breaking multi word definitions that _can_ be translated, like Big Bang.
![image](https://cloud.githubusercontent.com/assets/5481718/15556882/6a63c91c-228d-11e6-8944-26ca4a356edd.png)

**Comment by gliese1337** [comment]
That can't be done client-side. We don't reliably know whether or not they are trying to translate a phrase until we get the results back from Y-Lex. And even then, if it couldn't be translated, we may not know whether or not the thing that was not translated is a phrase, or just an unknown word.
