### ISSUE TITLE
Admin Bulk Editing Permissions: Let users know when they have been granted new permissions?

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#793]
Right now if a user requests something via a form, they are told the results of whether they got the permission granted or not via the notification system.

However, if an admin bulk adds permissions, the user has no idea they now have more access to features unless they experiment and check.

Should we notify users if they have been given new rights? Is there a reason not to notify them?

**Comment by JKJensen** [comment]
On that note, should we tell people that their account has been deleted?
For example, when they go to login, instead of saying: "Oh snap! Invalid username/password."
The error could be: "I'm sorry, but your account was deleted."

**Comment by gliese1337** [comment]
If the e-mail problem has been fixed, this should be happening automatically now. Fell free to re-open if we find that it isn't.
Notifying people on login that their account was deleted is a separate issue. That would require minor alterations to the database and major alterations to the process for deleting accounts.
