### ISSUE TITLE
Content from SCOLA cannot be created using the Add Content Pane

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#794]
Scola videos no longer upload in the Add Content pane

![scolacontentcantbeadded](https://cloud.githubusercontent.com/assets/5481718/15559261/e2d54d8e-229d-11e6-9db8-23a8ae2d42f3.gif)

This was the SCOLA content I was trying to add:
`https://56978dda1e4fa.streamlock.net/dashtest/dashtest/LO111631/LO111631_v08242015151739433/mp4:2.mp4/manifest.mpd`

Labelled as "wontfix" as we're not really focused on using SCOLA content right now.

**Comment by gliese1337** [comment]
That doesn't seem to be a bug. Looking at that link in a browser, it does indeed appear to be not valid, which means Ayamel is behaving correctly, and giving you the correct error message. That makes it SCOLA's problem.
