### ISSUE TITLE
Can't add individual content to an LMS

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#796]
When I view a content via a course, I'm met with two course related menu options: "Course" and "add to course."

However, clicking on Course->Add to LMS does not lead to a modal screen with information about how to connect the individual content to an LMS.

![nolmsaccessforcontent](https://cloud.githubusercontent.com/assets/5481718/15788734/2f49492e-2986-11e6-8ee5-c3cf18337ec8.gif)

Example video:
https://ayamel.byu.edu/course/398/content/2870

**Comment by gliese1337** [comment]
Fixed now, but we may have to re-open this when we get back to the LTI/xAPI permissions thing.
