### ISSUE TITLE
Remove download button for non-downloadable videos

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#797]
Unless a video is uploaded via our 25MB uploader, it cannot be downloaded from Ayamel.

<img width="213" alt="screenshot 2016-06-03 15 32 26" src="https://cloud.githubusercontent.com/assets/5481718/15793337/70270764-29a0-11e6-88f1-b3071d094c04.png">

So the download button should not display unless the content can be downloadable.

**Comment by gliese1337** [comment]
That's not entirely true. It's whether the source is a file or a stream that determines whether or not something can be downloaded; it's merely coincidental that the majority of resources with actual files backing them happen to have been created via Ayamel's file uploader.

Anyway, this is not a bug. Everything works as intended. But we can change that intended behavior if you like.
