### ISSUE TITLE
Captionaider: Adding to Line buffer should automatically activate both "Start Autofill" and "Start Auto-Cue"

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#799]
For the most part, users that use the "Add to line buffer" feature of Captionaider want to create subtitles via AutoCue/AutoFill.

<img width="420" alt="screenshot 2016-06-03 15 50 07" src="https://cloud.githubusercontent.com/assets/5481718/15793689/e09989ca-29a2-11e6-8baf-623e06f43323.png">

The act of adding a text file to the line buffer should trigger both AutoCue and AutoFill to activate. That ways users can immediately start timing their captions.

If the event users don't want to use AutoCue/Autofill, then they can still turn those options off after they have automatically turned on.

**Comment by gliese1337** [comment]
OK, this should work now. It's implemented as an internal switch, rather than totally hard-coded, so if anybody does not want this functionality, it'll be easy to add another menu item to allow users to turn it back off.
