### ISSUE TITLE
Ayamel Player: Change the "Sync with Media" button symbol in the transcript pane

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#801]
<img width="347" alt="screenshot 2016-06-06 16 35 19" src="https://cloud.githubusercontent.com/assets/5481718/15840124/fa5fe99e-2c04-11e6-85c5-9bb83b46440a.png">

In the transcript pane of the Ayamel player, we have a button that looks like a refresh symbol. However it actually stops the page from anchoring toward the current playing caption.

If possible, change the icon out and replace it with this:
![unsynctranscript](https://cloud.githubusercontent.com/assets/5481718/15840129/0abbf3b4-2c05-11e6-885e-fa43fb8330de.png)
(AI file and alternate versions available)

If not, this fontawesome icon will also suffice:
http://fontawesome.io/icon/link/

**Comment by gliese1337** [comment]
I'm not so sure that's a good idea. The double-arrow, usually circular double-arrow, is a well-established icon for "synchronize", used across a wide variety of software products. The link icon is  also well-established, but with a totally different meaning, which could be at least equally confusing- while synchronize does bear a significant resemblance to refresh, at least it is actually a different symbol!

And introducing a brand-new icon that we have invented also involves some learning curve.

**Comment by JKJensen** [comment]
You're right, a link is predominantly used for linking to web pages, making this confusing.

How about something like an anchor:
http://fontawesome.io/icon/anchor/

And the alt text when they hover over it is:
"Anchors current location"

**Comment by JKJensen** [comment]
This is amazing! Thank you Logan!
