### ISSUE TITLE
Commas in xAPI data

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#806]
Commas in wordText field are causing problem with exporting and importing data from the learning record store.

![image](https://cloud.githubusercontent.com/assets/7268293/16280838/c806ce3c-387e-11e6-9d0e-6b6006f7e6e6.png)

**Comment by verdude** [comment]
20b770c833843beb0b027422f40d9ce17d7a3ac5
