### ISSUE TITLE
Video Window Should Adjust to Tabs

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#807]
When a video has all options available, it seems the video window should adjust in accordance.

https://ayamel.byu.edu/content/3903

![image](https://cloud.githubusercontent.com/assets/7268293/16282410/e17b2726-3885-11e6-9325-cdc13f536fb0.png)

**Comment by DigitalProf** [comment]
While giving a presentation to Spanish teachers, the Mac and projector combination were such that the size of the video was small that the tabs were not visible. I was able to create this at will by decreasing the  video size and putting the bottom edge of the browser window over the bottom edge of the video:

![image](https://cloud.githubusercontent.com/assets/7268293/17420002/6fcdad0c-5a5d-11e6-8c10-78b2297789d0.png)

**Comment by gliese1337** [comment]
Fixed by scaling the size of the tabs down to fit the video window.
