### ISSUE TITLE
"Upload caption track" Drops Captions

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#809]
Working with https://ayamel.byu.edu/content/4078 and uploading the attached caption track (renamed to .TXT for uploading to GitHub), Ayamel drops several captions, the first two being 12 & 13.
[701_La_Familia_Digita (Original).srt.txt](https://github.com/BYU-ARCLITE/Ayamel-Examples/files/373789/701_La_Familia_Digita.Original.srt.txt)

**Comment by gliese1337** [comment]
Every dropped cue has an invalid timecode.

The first example is cue 12, which looks like this:

  12
  00:00:50,990 --> 00:00:54,40
  yo la verdad es que intentó

Note that the end time only contains 2 digits for the millisecond portion. A valid SRT timecode is *required* to have 3 digits.

I can, however, tweak our parser to be more lenient in this regard.
