### ISSUE TITLE
Cannot save in Configuration Dialogue Box

### ISSUE THREAD

**Issue by JKJensen** [BYU-ARCLITE/Ayamel-Examples#811]
Right now it's impossible for the save button to be pressed and new configurations to be saved.

Example content (Try to activate the subtitles in the configuration menu)
https://ayamel.byu.edu/content/4386

**Comment by DigitalProf** [comment]
I encountered the same problem with this video:
https://ayamel.byu.edu/content/4387

Here are the error messages received on the console:

![image](https://cloud.githubusercontent.com/assets/7268293/17593514/54e315f4-5fa3-11e6-9c19-8a753bdbd809.png)
