### ISSUE TITLE
Track Load Not Happening after Create Track

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#813]
If one creates a new track, then loads a track from disk, nothing happens, and the following error appears on the console:

![image](https://cloud.githubusercontent.com/assets/7268293/17645611/05515f20-6168-11e6-9fd5-953c60c4e05c.png)

**Comment by gliese1337** [comment]
Those warnings always appear. They've nothing to do with CaptionAider, unfortunately, so we'll have to investigate from scratch.

**Comment by gliese1337** [comment]
Can't replicate. Re-open with more specific replication instructions. The specific tracks that are failing to load would be good to have.

**Comment by DigitalProf** [comment]
[Here is the video link ](https://ayamel.byu.edu/content/4391)where this was happening. Here is the file with which it was happening (renamed so it is a TXT file):

[801 Para qué trabajamos.srt.txt](https://github.com/BYU-ARCLITE/Ayamel-Examples/files/416803/801.Para.que.trabajamos.srt.txt)
