### ISSUE TITLE
Error in CaptionAider while Creating and Saving Captions to File on Server

### ISSUE THREAD

**Issue by DigitalProf** [BYU-ARCLITE/Ayamel-Examples#843]
The following errors appeared on the console when trying to save a new caption file from CaptionAider

![image](https://user-images.githubusercontent.com/7268293/124318472-f11ea880-db35-11eb-866b-115052a5bcf6.png)

**Comment by verdude** [comment]
fixed here: https://github.com/BYU-ARCLITE/AyamelResourceAPI-Node/pull/6
